/*
 * BankPerkEligibility
 * This API will be used when the customer signs up for bank account to check their Perk Eligibility
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EligibilityRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-09T14:14:34.114-05:00")
public class EligibilityRequest {
  @SerializedName("tmoid")
  private String tmoid = null;

  @SerializedName("msisdn")
  private String msisdn = null;

  public EligibilityRequest tmoid(String tmoid) {
    this.tmoid = tmoid;
    return this;
  }

   /**
   * string is a predefined object from an igniteXml model - cabinet 1001760002 build 1001760247 key 1001760477
   * @return tmoid
  **/
  @ApiModelProperty(required = true, value = "string is a predefined object from an igniteXml model - cabinet 1001760002 build 1001760247 key 1001760477")
  public String getTmoid() {
    return tmoid;
  }

  public void setTmoid(String tmoid) {
    this.tmoid = tmoid;
  }

  public EligibilityRequest msisdn(String msisdn) {
    this.msisdn = msisdn;
    return this;
  }

   /**
   * string is a predefined object from an igniteXml model - cabinet 1001760002 build 1001760247 key 1001760477
   * @return msisdn
  **/
  @ApiModelProperty(value = "string is a predefined object from an igniteXml model - cabinet 1001760002 build 1001760247 key 1001760477")
  public String getMsisdn() {
    return msisdn;
  }

  public void setMsisdn(String msisdn) {
    this.msisdn = msisdn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EligibilityRequest eligibilityRequest = (EligibilityRequest) o;
    return Objects.equals(this.tmoid, eligibilityRequest.tmoid) &&
        Objects.equals(this.msisdn, eligibilityRequest.msisdn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tmoid, msisdn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EligibilityRequest {\n");
    
    sb.append("    tmoid: ").append(toIndentedString(tmoid)).append("\n");
    sb.append("    msisdn: ").append(toIndentedString(msisdn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

