/*
 * BankPerkEligibility
 * This API will be used when the customer signs up for bank account to check their Perk Eligibility
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * As defined in http://api-standards.apps.px-npe01.cf.t-mobile.com/http/status-codes/error-response-format/
 */
@ApiModel(description = "As defined in http://api-standards.apps.px-npe01.cf.t-mobile.com/http/status-codes/error-response-format/")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-09T14:14:34.114-05:00")
public class ErrorResponseErrors {
  @SerializedName("code")
  private String code = null;

  @SerializedName("userMessage")
  private String userMessage = null;

  @SerializedName("systemMessage")
  private String systemMessage = null;

  @SerializedName("detailLink")
  private String detailLink = null;

  public ErrorResponseErrors code(String code) {
    this.code = code;
    return this;
  }

   /**
   * A succinct, domain-specific, human-readable text string to identify the type of error for the given status code
   * @return code
  **/
  @ApiModelProperty(example = "ProductNotFound", required = true, value = "A succinct, domain-specific, human-readable text string to identify the type of error for the given status code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ErrorResponseErrors userMessage(String userMessage) {
    this.userMessage = userMessage;
    return this;
  }

   /**
   * A human-readable message describing the error.
   * @return userMessage
  **/
  @ApiModelProperty(example = "Failed to find product.", required = true, value = "A human-readable message describing the error.")
  public String getUserMessage() {
    return userMessage;
  }

  public void setUserMessage(String userMessage) {
    this.userMessage = userMessage;
  }

  public ErrorResponseErrors systemMessage(String systemMessage) {
    this.systemMessage = systemMessage;
    return this;
  }

   /**
   * Text that provides a more detailed technical explanation of the error
   * @return systemMessage
  **/
  @ApiModelProperty(example = "PRODUCT_NOT_FOUND", value = "Text that provides a more detailed technical explanation of the error")
  public String getSystemMessage() {
    return systemMessage;
  }

  public void setSystemMessage(String systemMessage) {
    this.systemMessage = systemMessage;
  }

  public ErrorResponseErrors detailLink(String detailLink) {
    this.detailLink = detailLink;
    return this;
  }

   /**
   * link to custom information providing greater detail on error or errors
   * @return detailLink
  **/
  @ApiModelProperty(example = "http://aaa.bbb.ccc/", value = "link to custom information providing greater detail on error or errors")
  public String getDetailLink() {
    return detailLink;
  }

  public void setDetailLink(String detailLink) {
    this.detailLink = detailLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponseErrors errorResponseErrors = (ErrorResponseErrors) o;
    return Objects.equals(this.code, errorResponseErrors.code) &&
        Objects.equals(this.userMessage, errorResponseErrors.userMessage) &&
        Objects.equals(this.systemMessage, errorResponseErrors.systemMessage) &&
        Objects.equals(this.detailLink, errorResponseErrors.detailLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, userMessage, systemMessage, detailLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponseErrors {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    userMessage: ").append(toIndentedString(userMessage)).append("\n");
    sb.append("    systemMessage: ").append(toIndentedString(systemMessage)).append("\n");
    sb.append("    detailLink: ").append(toIndentedString(detailLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

