/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.iam.ResponseBillingAccount;
import com.tmobile.finance.iam.ResponseIAMUniverse;
import com.tmobile.finance.iam.ResponseLinkedLines;
import com.tmobile.finance.iam.ResponseNsmResponse;
import com.tmobile.finance.iam.ResponsePermissions;
import com.tmobile.finance.iam.ResponsePrivacy;
import com.tmobile.finance.iam.ResponseTMobileIdentity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Response
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class Response {
  @SerializedName("nsmResponse")
  private ResponseNsmResponse nsmResponse = null;

  @SerializedName("executionTime")
  private String executionTime = null;

  @SerializedName("ObjectClass")
  private String objectClass = null;

  @SerializedName("msisdn")
  private String msisdn = null;

  @SerializedName("UserId")
  private String userId = null;

  @SerializedName("Email")
  private String email = null;

  @SerializedName("TMobileIdentity")
  @JsonProperty("TMobileIdentity")
  private ResponseTMobileIdentity tmobileIdentity = null;

  @SerializedName("LinkedLines")
  private ResponseLinkedLines linkedLines = null;

  @SerializedName("BillingAccount")
  private List<ResponseBillingAccount> billingAccount = null;

  @SerializedName("Permissions")
  private ResponsePermissions permissions = null;

  @SerializedName("IAMUniverse")
  private ResponseIAMUniverse iaMUniverse = null;

  @SerializedName("Privacy")
  private ResponsePrivacy privacy = null;

  public Response nsmResponse(ResponseNsmResponse nsmResponse) {
    this.nsmResponse = nsmResponse;
    return this;
  }

   /**
   * Get nsmResponse
   * @return nsmResponse
  **/
  @ApiModelProperty(value = "")
  public ResponseNsmResponse getNsmResponse() {
    return nsmResponse;
  }

  public void setNsmResponse(ResponseNsmResponse nsmResponse) {
    this.nsmResponse = nsmResponse;
  }

  public Response executionTime(String executionTime) {
    this.executionTime = executionTime;
    return this;
  }

   /**
   * Get executionTime
   * @return executionTime
  **/
  @ApiModelProperty(value = "")
  public String getExecutionTime() {
    return executionTime;
  }

  public void setExecutionTime(String executionTime) {
    this.executionTime = executionTime;
  }

  public Response objectClass(String objectClass) {
    this.objectClass = objectClass;
    return this;
  }

   /**
   * Get objectClass
   * @return objectClass
  **/
  @ApiModelProperty(value = "")
  public String getObjectClass() {
    return objectClass;
  }

  public void setObjectClass(String objectClass) {
    this.objectClass = objectClass;
  }

  public Response msisdn(String msisdn) {
    this.msisdn = msisdn;
    return this;
  }

   /**
   * Get msisdn
   * @return msisdn
  **/
  @ApiModelProperty(value = "")
  public String getMsisdn() {
    return msisdn;
  }

  public void setMsisdn(String msisdn) {
    this.msisdn = msisdn;
  }

  public Response userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public Response email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Response tmobileIdentity(ResponseTMobileIdentity tmobileIdentity) {
    this.tmobileIdentity = tmobileIdentity;
    return this;
  }

   /**
   * Get tmobileIdentity
   * @return tmobileIdentity
  **/
  @ApiModelProperty(value = "")
  public ResponseTMobileIdentity getTmobileIdentity() {
    return tmobileIdentity;
  }

  public void setTmobileIdentity(ResponseTMobileIdentity tmobileIdentity) {
    this.tmobileIdentity = tmobileIdentity;
  }

  public Response linkedLines(ResponseLinkedLines linkedLines) {
    this.linkedLines = linkedLines;
    return this;
  }

   /**
   * Get linkedLines
   * @return linkedLines
  **/
  @ApiModelProperty(value = "")
  public ResponseLinkedLines getLinkedLines() {
    return linkedLines;
  }

  public void setLinkedLines(ResponseLinkedLines linkedLines) {
    this.linkedLines = linkedLines;
  }

  public Response billingAccount(List<ResponseBillingAccount> billingAccount) {
    this.billingAccount = billingAccount;
    return this;
  }

  public Response addBillingAccountItem(ResponseBillingAccount billingAccountItem) {
    if (this.billingAccount == null) {
      this.billingAccount = new ArrayList<ResponseBillingAccount>();
    }
    this.billingAccount.add(billingAccountItem);
    return this;
  }

   /**
   * Get billingAccount
   * @return billingAccount
  **/
  @ApiModelProperty(value = "")
  public List<ResponseBillingAccount> getBillingAccount() {
    return billingAccount;
  }

  public void setBillingAccount(List<ResponseBillingAccount> billingAccount) {
    this.billingAccount = billingAccount;
  }

  public Response permissions(ResponsePermissions permissions) {
    this.permissions = permissions;
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @ApiModelProperty(value = "")
  public ResponsePermissions getPermissions() {
    return permissions;
  }

  public void setPermissions(ResponsePermissions permissions) {
    this.permissions = permissions;
  }

  public Response iaMUniverse(ResponseIAMUniverse iaMUniverse) {
    this.iaMUniverse = iaMUniverse;
    return this;
  }

   /**
   * Get iaMUniverse
   * @return iaMUniverse
  **/
  @ApiModelProperty(value = "")
  public ResponseIAMUniverse getIaMUniverse() {
    return iaMUniverse;
  }

  public void setIaMUniverse(ResponseIAMUniverse iaMUniverse) {
    this.iaMUniverse = iaMUniverse;
  }

  public Response privacy(ResponsePrivacy privacy) {
    this.privacy = privacy;
    return this;
  }

   /**
   * Get privacy
   * @return privacy
  **/
  @ApiModelProperty(value = "")
  public ResponsePrivacy getPrivacy() {
    return privacy;
  }

  public void setPrivacy(ResponsePrivacy privacy) {
    this.privacy = privacy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Response response = (Response) o;
    return Objects.equals(this.nsmResponse, response.nsmResponse) &&
        Objects.equals(this.executionTime, response.executionTime) &&
        Objects.equals(this.objectClass, response.objectClass) &&
        Objects.equals(this.msisdn, response.msisdn) &&
        Objects.equals(this.userId, response.userId) &&
        Objects.equals(this.email, response.email) &&
        Objects.equals(this.tmobileIdentity, response.tmobileIdentity) &&
        Objects.equals(this.linkedLines, response.linkedLines) &&
        Objects.equals(this.billingAccount, response.billingAccount) &&
        Objects.equals(this.permissions, response.permissions) &&
        Objects.equals(this.iaMUniverse, response.iaMUniverse) &&
        Objects.equals(this.privacy, response.privacy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nsmResponse, executionTime, objectClass, msisdn, userId, email, tmobileIdentity, linkedLines, billingAccount, permissions, iaMUniverse, privacy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Response {\n");
    
    sb.append("    nsmResponse: ").append(toIndentedString(nsmResponse)).append("\n");
    sb.append("    executionTime: ").append(toIndentedString(executionTime)).append("\n");
    sb.append("    objectClass: ").append(toIndentedString(objectClass)).append("\n");
    sb.append("    msisdn: ").append(toIndentedString(msisdn)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    tmobileIdentity: ").append(toIndentedString(tmobileIdentity)).append("\n");
    sb.append("    linkedLines: ").append(toIndentedString(linkedLines)).append("\n");
    sb.append("    billingAccount: ").append(toIndentedString(billingAccount)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    iaMUniverse: ").append(toIndentedString(iaMUniverse)).append("\n");
    sb.append("    privacy: ").append(toIndentedString(privacy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

