/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.iam.ResponsePrivacyAssociatedLineAccountsResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ResponsePrivacyAssociatedLineAccounts
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponsePrivacyAssociatedLineAccounts {
  @SerializedName("response")
  private List<ResponsePrivacyAssociatedLineAccountsResponse> response = null;

  public ResponsePrivacyAssociatedLineAccounts response(List<ResponsePrivacyAssociatedLineAccountsResponse> response) {
    this.response = response;
    return this;
  }

  public ResponsePrivacyAssociatedLineAccounts addResponseItem(ResponsePrivacyAssociatedLineAccountsResponse responseItem) {
    if (this.response == null) {
      this.response = new ArrayList<ResponsePrivacyAssociatedLineAccountsResponse>();
    }
    this.response.add(responseItem);
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  @ApiModelProperty(value = "")
  public List<ResponsePrivacyAssociatedLineAccountsResponse> getResponse() {
    return response;
  }

  public void setResponse(List<ResponsePrivacyAssociatedLineAccountsResponse> response) {
    this.response = response;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePrivacyAssociatedLineAccounts responsePrivacyAssociatedLineAccounts = (ResponsePrivacyAssociatedLineAccounts) o;
    return Objects.equals(this.response, responsePrivacyAssociatedLineAccounts.response);
  }

  @Override
  public int hashCode() {
    return Objects.hash(response);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePrivacyAssociatedLineAccounts {\n");
    
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

