/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.iam.ResponseLines;
import com.tmobile.finance.iam.ResponseTMobileIdentityAccountDetailsAccess;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ResponseBillingAccount
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseBillingAccount {
  @SerializedName("Ban")
  private String ban = null;

  @SerializedName("BillCycleDay")
  private String billCycleDay = null;

  @SerializedName("ZipCode")
  private String zipCode = null;

  @SerializedName("FirstName")
  private String firstName = null;

  @SerializedName("LastName")
  private String lastName = null;

  @SerializedName("BirthDate")
  private String birthDate = null;

  @SerializedName("Lines")
  private List<ResponseLines> lines = null;

  @SerializedName("Access")
  private ResponseTMobileIdentityAccountDetailsAccess access = null;

  public ResponseBillingAccount ban(String ban) {
    this.ban = ban;
    return this;
  }

   /**
   * Get ban
   * @return ban
  **/
  @ApiModelProperty(value = "")
  public String getBan() {
    return ban;
  }

  public void setBan(String ban) {
    this.ban = ban;
  }

  public ResponseBillingAccount billCycleDay(String billCycleDay) {
    this.billCycleDay = billCycleDay;
    return this;
  }

   /**
   * Get billCycleDay
   * @return billCycleDay
  **/
  @ApiModelProperty(value = "")
  public String getBillCycleDay() {
    return billCycleDay;
  }

  public void setBillCycleDay(String billCycleDay) {
    this.billCycleDay = billCycleDay;
  }

  public ResponseBillingAccount zipCode(String zipCode) {
    this.zipCode = zipCode;
    return this;
  }

   /**
   * Get zipCode
   * @return zipCode
  **/
  @ApiModelProperty(value = "")
  public String getZipCode() {
    return zipCode;
  }

  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  public ResponseBillingAccount firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ResponseBillingAccount lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public ResponseBillingAccount birthDate(String birthDate) {
    this.birthDate = birthDate;
    return this;
  }

   /**
   * Get birthDate
   * @return birthDate
  **/
  @ApiModelProperty(value = "")
  public String getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(String birthDate) {
    this.birthDate = birthDate;
  }

  public ResponseBillingAccount lines(List<ResponseLines> lines) {
    this.lines = lines;
    return this;
  }

  public ResponseBillingAccount addLinesItem(ResponseLines linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<ResponseLines>();
    }
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Get lines
   * @return lines
  **/
  @ApiModelProperty(value = "")
  public List<ResponseLines> getLines() {
    return lines;
  }

  public void setLines(List<ResponseLines> lines) {
    this.lines = lines;
  }

  public ResponseBillingAccount access(ResponseTMobileIdentityAccountDetailsAccess access) {
    this.access = access;
    return this;
  }

   /**
   * Get access
   * @return access
  **/
  @ApiModelProperty(value = "")
  public ResponseTMobileIdentityAccountDetailsAccess getAccess() {
    return access;
  }

  public void setAccess(ResponseTMobileIdentityAccountDetailsAccess access) {
    this.access = access;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseBillingAccount responseBillingAccount = (ResponseBillingAccount) o;
    return Objects.equals(this.ban, responseBillingAccount.ban) &&
        Objects.equals(this.billCycleDay, responseBillingAccount.billCycleDay) &&
        Objects.equals(this.zipCode, responseBillingAccount.zipCode) &&
        Objects.equals(this.firstName, responseBillingAccount.firstName) &&
        Objects.equals(this.lastName, responseBillingAccount.lastName) &&
        Objects.equals(this.birthDate, responseBillingAccount.birthDate) &&
        Objects.equals(this.lines, responseBillingAccount.lines) &&
        Objects.equals(this.access, responseBillingAccount.access);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ban, billCycleDay, zipCode, firstName, lastName, birthDate, lines, access);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseBillingAccount {\n");
    
    sb.append("    ban: ").append(toIndentedString(ban)).append("\n");
    sb.append("    billCycleDay: ").append(toIndentedString(billCycleDay)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

