/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.iam.ResponseLinkedLinesDefaultLine;
import com.tmobile.finance.iam.ResponseTMobileIdentityAccountDetailsAccess;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponseLinkedLines
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseLinkedLines {
  @SerializedName("DefaultLine")
  private ResponseLinkedLinesDefaultLine defaultLine = null;

  @SerializedName("Access")
  private ResponseTMobileIdentityAccountDetailsAccess access = null;

  public ResponseLinkedLines defaultLine(ResponseLinkedLinesDefaultLine defaultLine) {
    this.defaultLine = defaultLine;
    return this;
  }

   /**
   * Get defaultLine
   * @return defaultLine
  **/
  @ApiModelProperty(value = "")
  public ResponseLinkedLinesDefaultLine getDefaultLine() {
    return defaultLine;
  }

  public void setDefaultLine(ResponseLinkedLinesDefaultLine defaultLine) {
    this.defaultLine = defaultLine;
  }

  public ResponseLinkedLines access(ResponseTMobileIdentityAccountDetailsAccess access) {
    this.access = access;
    return this;
  }

   /**
   * Get access
   * @return access
  **/
  @ApiModelProperty(value = "")
  public ResponseTMobileIdentityAccountDetailsAccess getAccess() {
    return access;
  }

  public void setAccess(ResponseTMobileIdentityAccountDetailsAccess access) {
    this.access = access;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseLinkedLines responseLinkedLines = (ResponseLinkedLines) o;
    return Objects.equals(this.defaultLine, responseLinkedLines.defaultLine) &&
        Objects.equals(this.access, responseLinkedLines.access);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultLine, access);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseLinkedLines {\n");
    
    sb.append("    defaultLine: ").append(toIndentedString(defaultLine)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

