/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.iam.ResponseIAMUniverseAccountDetails;
import com.tmobile.finance.iam.ResponseIAMUniverseAccountStatus;
import com.tmobile.finance.iam.ResponseIAMUniversePasswordsandSecurity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponseIAMUniverseAccountInformation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseIAMUniverseAccountInformation {
  @SerializedName("AccountDetails")
  private ResponseIAMUniverseAccountDetails accountDetails = null;

  @SerializedName("AccountStatus")
  private ResponseIAMUniverseAccountStatus accountStatus = null;

  @SerializedName("PasswordsandSecurity")
  private ResponseIAMUniversePasswordsandSecurity passwordsandSecurity = null;

  public ResponseIAMUniverseAccountInformation accountDetails(ResponseIAMUniverseAccountDetails accountDetails) {
    this.accountDetails = accountDetails;
    return this;
  }

   /**
   * Get accountDetails
   * @return accountDetails
  **/
  @ApiModelProperty(value = "")
  public ResponseIAMUniverseAccountDetails getAccountDetails() {
    return accountDetails;
  }

  public void setAccountDetails(ResponseIAMUniverseAccountDetails accountDetails) {
    this.accountDetails = accountDetails;
  }

  public ResponseIAMUniverseAccountInformation accountStatus(ResponseIAMUniverseAccountStatus accountStatus) {
    this.accountStatus = accountStatus;
    return this;
  }

   /**
   * Get accountStatus
   * @return accountStatus
  **/
  @ApiModelProperty(value = "")
  public ResponseIAMUniverseAccountStatus getAccountStatus() {
    return accountStatus;
  }

  public void setAccountStatus(ResponseIAMUniverseAccountStatus accountStatus) {
    this.accountStatus = accountStatus;
  }

  public ResponseIAMUniverseAccountInformation passwordsandSecurity(ResponseIAMUniversePasswordsandSecurity passwordsandSecurity) {
    this.passwordsandSecurity = passwordsandSecurity;
    return this;
  }

   /**
   * Get passwordsandSecurity
   * @return passwordsandSecurity
  **/
  @ApiModelProperty(value = "")
  public ResponseIAMUniversePasswordsandSecurity getPasswordsandSecurity() {
    return passwordsandSecurity;
  }

  public void setPasswordsandSecurity(ResponseIAMUniversePasswordsandSecurity passwordsandSecurity) {
    this.passwordsandSecurity = passwordsandSecurity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseIAMUniverseAccountInformation responseIAMUniverseAccountInformation = (ResponseIAMUniverseAccountInformation) o;
    return Objects.equals(this.accountDetails, responseIAMUniverseAccountInformation.accountDetails) &&
        Objects.equals(this.accountStatus, responseIAMUniverseAccountInformation.accountStatus) &&
        Objects.equals(this.passwordsandSecurity, responseIAMUniverseAccountInformation.passwordsandSecurity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountDetails, accountStatus, passwordsandSecurity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseIAMUniverseAccountInformation {\n");
    
    sb.append("    accountDetails: ").append(toIndentedString(accountDetails)).append("\n");
    sb.append("    accountStatus: ").append(toIndentedString(accountStatus)).append("\n");
    sb.append("    passwordsandSecurity: ").append(toIndentedString(passwordsandSecurity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

