/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.iam.ResponsePrivacyAssociatedLineAccounts;
import com.tmobile.finance.iam.ResponsePrivacyAvailableLists;
import com.tmobile.finance.iam.ResponsePrivacyConsents;
import com.tmobile.finance.iam.ResponsePrivacyContactPreferences;
import com.tmobile.finance.iam.ResponsePrivacyOfferDelivery;
import com.tmobile.finance.iam.ResponsePrivacyOffers;
import com.tmobile.finance.iam.ResponseTMobileIdentityAccountDetailsAccess;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ResponsePrivacy
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponsePrivacy {
  @SerializedName("OfferDelivery")
  private List<ResponsePrivacyOfferDelivery> offerDelivery = null;

  @SerializedName("ContactPreferences")
  private List<ResponsePrivacyContactPreferences> contactPreferences = null;

  @SerializedName("Offers")
  private List<ResponsePrivacyOffers> offers = null;

  @SerializedName("Consents")
  private ResponsePrivacyConsents consents = null;

  @SerializedName("AssociatedLineAccounts")
  private ResponsePrivacyAssociatedLineAccounts associatedLineAccounts = null;

  @SerializedName("AvailableLists")
  private List<ResponsePrivacyAvailableLists> availableLists = null;

  @SerializedName("Access")
  private ResponseTMobileIdentityAccountDetailsAccess access = null;

  public ResponsePrivacy offerDelivery(List<ResponsePrivacyOfferDelivery> offerDelivery) {
    this.offerDelivery = offerDelivery;
    return this;
  }

  public ResponsePrivacy addOfferDeliveryItem(ResponsePrivacyOfferDelivery offerDeliveryItem) {
    if (this.offerDelivery == null) {
      this.offerDelivery = new ArrayList<ResponsePrivacyOfferDelivery>();
    }
    this.offerDelivery.add(offerDeliveryItem);
    return this;
  }

   /**
   * Get offerDelivery
   * @return offerDelivery
  **/
  @ApiModelProperty(value = "")
  public List<ResponsePrivacyOfferDelivery> getOfferDelivery() {
    return offerDelivery;
  }

  public void setOfferDelivery(List<ResponsePrivacyOfferDelivery> offerDelivery) {
    this.offerDelivery = offerDelivery;
  }

  public ResponsePrivacy contactPreferences(List<ResponsePrivacyContactPreferences> contactPreferences) {
    this.contactPreferences = contactPreferences;
    return this;
  }

  public ResponsePrivacy addContactPreferencesItem(ResponsePrivacyContactPreferences contactPreferencesItem) {
    if (this.contactPreferences == null) {
      this.contactPreferences = new ArrayList<ResponsePrivacyContactPreferences>();
    }
    this.contactPreferences.add(contactPreferencesItem);
    return this;
  }

   /**
   * Get contactPreferences
   * @return contactPreferences
  **/
  @ApiModelProperty(value = "")
  public List<ResponsePrivacyContactPreferences> getContactPreferences() {
    return contactPreferences;
  }

  public void setContactPreferences(List<ResponsePrivacyContactPreferences> contactPreferences) {
    this.contactPreferences = contactPreferences;
  }

  public ResponsePrivacy offers(List<ResponsePrivacyOffers> offers) {
    this.offers = offers;
    return this;
  }

  public ResponsePrivacy addOffersItem(ResponsePrivacyOffers offersItem) {
    if (this.offers == null) {
      this.offers = new ArrayList<ResponsePrivacyOffers>();
    }
    this.offers.add(offersItem);
    return this;
  }

   /**
   * Get offers
   * @return offers
  **/
  @ApiModelProperty(value = "")
  public List<ResponsePrivacyOffers> getOffers() {
    return offers;
  }

  public void setOffers(List<ResponsePrivacyOffers> offers) {
    this.offers = offers;
  }

  public ResponsePrivacy consents(ResponsePrivacyConsents consents) {
    this.consents = consents;
    return this;
  }

   /**
   * Get consents
   * @return consents
  **/
  @ApiModelProperty(value = "")
  public ResponsePrivacyConsents getConsents() {
    return consents;
  }

  public void setConsents(ResponsePrivacyConsents consents) {
    this.consents = consents;
  }

  public ResponsePrivacy associatedLineAccounts(ResponsePrivacyAssociatedLineAccounts associatedLineAccounts) {
    this.associatedLineAccounts = associatedLineAccounts;
    return this;
  }

   /**
   * Get associatedLineAccounts
   * @return associatedLineAccounts
  **/
  @ApiModelProperty(value = "")
  public ResponsePrivacyAssociatedLineAccounts getAssociatedLineAccounts() {
    return associatedLineAccounts;
  }

  public void setAssociatedLineAccounts(ResponsePrivacyAssociatedLineAccounts associatedLineAccounts) {
    this.associatedLineAccounts = associatedLineAccounts;
  }

  public ResponsePrivacy availableLists(List<ResponsePrivacyAvailableLists> availableLists) {
    this.availableLists = availableLists;
    return this;
  }

  public ResponsePrivacy addAvailableListsItem(ResponsePrivacyAvailableLists availableListsItem) {
    if (this.availableLists == null) {
      this.availableLists = new ArrayList<ResponsePrivacyAvailableLists>();
    }
    this.availableLists.add(availableListsItem);
    return this;
  }

   /**
   * Get availableLists
   * @return availableLists
  **/
  @ApiModelProperty(value = "")
  public List<ResponsePrivacyAvailableLists> getAvailableLists() {
    return availableLists;
  }

  public void setAvailableLists(List<ResponsePrivacyAvailableLists> availableLists) {
    this.availableLists = availableLists;
  }

  public ResponsePrivacy access(ResponseTMobileIdentityAccountDetailsAccess access) {
    this.access = access;
    return this;
  }

   /**
   * Get access
   * @return access
  **/
  @ApiModelProperty(value = "")
  public ResponseTMobileIdentityAccountDetailsAccess getAccess() {
    return access;
  }

  public void setAccess(ResponseTMobileIdentityAccountDetailsAccess access) {
    this.access = access;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePrivacy responsePrivacy = (ResponsePrivacy) o;
    return Objects.equals(this.offerDelivery, responsePrivacy.offerDelivery) &&
        Objects.equals(this.contactPreferences, responsePrivacy.contactPreferences) &&
        Objects.equals(this.offers, responsePrivacy.offers) &&
        Objects.equals(this.consents, responsePrivacy.consents) &&
        Objects.equals(this.associatedLineAccounts, responsePrivacy.associatedLineAccounts) &&
        Objects.equals(this.availableLists, responsePrivacy.availableLists) &&
        Objects.equals(this.access, responsePrivacy.access);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offerDelivery, contactPreferences, offers, consents, associatedLineAccounts, availableLists, access);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePrivacy {\n");
    
    sb.append("    offerDelivery: ").append(toIndentedString(offerDelivery)).append("\n");
    sb.append("    contactPreferences: ").append(toIndentedString(contactPreferences)).append("\n");
    sb.append("    offers: ").append(toIndentedString(offers)).append("\n");
    sb.append("    consents: ").append(toIndentedString(consents)).append("\n");
    sb.append("    associatedLineAccounts: ").append(toIndentedString(associatedLineAccounts)).append("\n");
    sb.append("    availableLists: ").append(toIndentedString(availableLists)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

