/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponsePermissionsImplicitPermissions
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponsePermissionsImplicitPermissions {
  @SerializedName("msisdn")
  private String msisdn = null;

  @SerializedName("IMSI")
  private String IMSI = null;

  @SerializedName("BAN")
  private String BAN = null;

  @SerializedName("IsLineGrantable")
  private Boolean isLineGrantable = null;

  @SerializedName("PermissionType")
  private String permissionType = null;

  @SerializedName("IsPrimaryMSISDN")
  private Boolean isPrimaryMSISDN = null;

  @SerializedName("AccountStatus")
  private String accountStatus = null;

  @SerializedName("CustomerType")
  private String customerType = null;

  public ResponsePermissionsImplicitPermissions msisdn(String msisdn) {
    this.msisdn = msisdn;
    return this;
  }

   /**
   * Get msisdn
   * @return msisdn
  **/
  @ApiModelProperty(value = "")
  public String getMsisdn() {
    return msisdn;
  }

  public void setMsisdn(String msisdn) {
    this.msisdn = msisdn;
  }

  public ResponsePermissionsImplicitPermissions IMSI(String IMSI) {
    this.IMSI = IMSI;
    return this;
  }

   /**
   * Get IMSI
   * @return IMSI
  **/
  @ApiModelProperty(value = "")
  public String getIMSI() {
    return IMSI;
  }

  public void setIMSI(String IMSI) {
    this.IMSI = IMSI;
  }

  public ResponsePermissionsImplicitPermissions BAN(String BAN) {
    this.BAN = BAN;
    return this;
  }

   /**
   * Get BAN
   * @return BAN
  **/
  @ApiModelProperty(value = "")
  public String getBAN() {
    return BAN;
  }

  public void setBAN(String BAN) {
    this.BAN = BAN;
  }

  public ResponsePermissionsImplicitPermissions isLineGrantable(Boolean isLineGrantable) {
    this.isLineGrantable = isLineGrantable;
    return this;
  }

   /**
   * Get isLineGrantable
   * @return isLineGrantable
  **/
  @ApiModelProperty(value = "")
  public Boolean getIsLineGrantable() {
    return isLineGrantable;
  }

  public void setIsLineGrantable(Boolean isLineGrantable) {
    this.isLineGrantable = isLineGrantable;
  }

  public ResponsePermissionsImplicitPermissions permissionType(String permissionType) {
    this.permissionType = permissionType;
    return this;
  }

   /**
   * Get permissionType
   * @return permissionType
  **/
  @ApiModelProperty(value = "")
  public String getPermissionType() {
    return permissionType;
  }

  public void setPermissionType(String permissionType) {
    this.permissionType = permissionType;
  }

  public ResponsePermissionsImplicitPermissions isPrimaryMSISDN(Boolean isPrimaryMSISDN) {
    this.isPrimaryMSISDN = isPrimaryMSISDN;
    return this;
  }

   /**
   * Get isPrimaryMSISDN
   * @return isPrimaryMSISDN
  **/
  @ApiModelProperty(value = "")
  public Boolean getIsPrimaryMSISDN() {
    return isPrimaryMSISDN;
  }

  public void setIsPrimaryMSISDN(Boolean isPrimaryMSISDN) {
    this.isPrimaryMSISDN = isPrimaryMSISDN;
  }

  public ResponsePermissionsImplicitPermissions accountStatus(String accountStatus) {
    this.accountStatus = accountStatus;
    return this;
  }

   /**
   * Get accountStatus
   * @return accountStatus
  **/
  @ApiModelProperty(value = "")
  public String getAccountStatus() {
    return accountStatus;
  }

  public void setAccountStatus(String accountStatus) {
    this.accountStatus = accountStatus;
  }

  public ResponsePermissionsImplicitPermissions customerType(String customerType) {
    this.customerType = customerType;
    return this;
  }

   /**
   * Get customerType
   * @return customerType
  **/
  @ApiModelProperty(value = "")
  public String getCustomerType() {
    return customerType;
  }

  public void setCustomerType(String customerType) {
    this.customerType = customerType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePermissionsImplicitPermissions responsePermissionsImplicitPermissions = (ResponsePermissionsImplicitPermissions) o;
    return Objects.equals(this.msisdn, responsePermissionsImplicitPermissions.msisdn) &&
        Objects.equals(this.IMSI, responsePermissionsImplicitPermissions.IMSI) &&
        Objects.equals(this.BAN, responsePermissionsImplicitPermissions.BAN) &&
        Objects.equals(this.isLineGrantable, responsePermissionsImplicitPermissions.isLineGrantable) &&
        Objects.equals(this.permissionType, responsePermissionsImplicitPermissions.permissionType) &&
        Objects.equals(this.isPrimaryMSISDN, responsePermissionsImplicitPermissions.isPrimaryMSISDN) &&
        Objects.equals(this.accountStatus, responsePermissionsImplicitPermissions.accountStatus) &&
        Objects.equals(this.customerType, responsePermissionsImplicitPermissions.customerType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(msisdn, IMSI, BAN, isLineGrantable, permissionType, isPrimaryMSISDN, accountStatus, customerType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePermissionsImplicitPermissions {\n");
    
    sb.append("    msisdn: ").append(toIndentedString(msisdn)).append("\n");
    sb.append("    IMSI: ").append(toIndentedString(IMSI)).append("\n");
    sb.append("    BAN: ").append(toIndentedString(BAN)).append("\n");
    sb.append("    isLineGrantable: ").append(toIndentedString(isLineGrantable)).append("\n");
    sb.append("    permissionType: ").append(toIndentedString(permissionType)).append("\n");
    sb.append("    isPrimaryMSISDN: ").append(toIndentedString(isPrimaryMSISDN)).append("\n");
    sb.append("    accountStatus: ").append(toIndentedString(accountStatus)).append("\n");
    sb.append("    customerType: ").append(toIndentedString(customerType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

