/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.iam.ResponseTMobileIdentityAccountDetailsAccess;
import com.tmobile.finance.iam.ResponseTMobileIdentityAccountDetailsAccountStatus;
import com.tmobile.finance.iam.ResponseTMobileIdentityAccountDetailsAuthentication;
import com.tmobile.finance.iam.ResponseTMobileIdentityAccountDetailsAvailableLists;
import com.tmobile.finance.iam.ResponseTMobileIdentityAccountDetailsPasswords;
import com.tmobile.finance.iam.ResponseTMobileIdentityAccountDetailsSecurity;
import com.tmobile.finance.iam.ResponseTMobileIdentityAccountDetailsUser;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponseTMobileIdentityAccountDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseTMobileIdentityAccountDetails {
  @SerializedName("User")
  private ResponseTMobileIdentityAccountDetailsUser user = null;

  @SerializedName("Authentication")
  private ResponseTMobileIdentityAccountDetailsAuthentication authentication = null;

  @SerializedName("Security")
  private ResponseTMobileIdentityAccountDetailsSecurity security = null;

  @SerializedName("Passwords")
  private ResponseTMobileIdentityAccountDetailsPasswords passwords = null;

  @SerializedName("AccountStatus")
  private ResponseTMobileIdentityAccountDetailsAccountStatus accountStatus = null;

  @SerializedName("Access")
  private ResponseTMobileIdentityAccountDetailsAccess access = null;

  @SerializedName("AvailableLists")
  private ResponseTMobileIdentityAccountDetailsAvailableLists availableLists = null;

  public ResponseTMobileIdentityAccountDetails user(ResponseTMobileIdentityAccountDetailsUser user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(value = "")
  public ResponseTMobileIdentityAccountDetailsUser getUser() {
    return user;
  }

  public void setUser(ResponseTMobileIdentityAccountDetailsUser user) {
    this.user = user;
  }

  public ResponseTMobileIdentityAccountDetails authentication(ResponseTMobileIdentityAccountDetailsAuthentication authentication) {
    this.authentication = authentication;
    return this;
  }

   /**
   * Get authentication
   * @return authentication
  **/
  @ApiModelProperty(value = "")
  public ResponseTMobileIdentityAccountDetailsAuthentication getAuthentication() {
    return authentication;
  }

  public void setAuthentication(ResponseTMobileIdentityAccountDetailsAuthentication authentication) {
    this.authentication = authentication;
  }

  public ResponseTMobileIdentityAccountDetails security(ResponseTMobileIdentityAccountDetailsSecurity security) {
    this.security = security;
    return this;
  }

   /**
   * Get security
   * @return security
  **/
  @ApiModelProperty(value = "")
  public ResponseTMobileIdentityAccountDetailsSecurity getSecurity() {
    return security;
  }

  public void setSecurity(ResponseTMobileIdentityAccountDetailsSecurity security) {
    this.security = security;
  }

  public ResponseTMobileIdentityAccountDetails passwords(ResponseTMobileIdentityAccountDetailsPasswords passwords) {
    this.passwords = passwords;
    return this;
  }

   /**
   * Get passwords
   * @return passwords
  **/
  @ApiModelProperty(value = "")
  public ResponseTMobileIdentityAccountDetailsPasswords getPasswords() {
    return passwords;
  }

  public void setPasswords(ResponseTMobileIdentityAccountDetailsPasswords passwords) {
    this.passwords = passwords;
  }

  public ResponseTMobileIdentityAccountDetails accountStatus(ResponseTMobileIdentityAccountDetailsAccountStatus accountStatus) {
    this.accountStatus = accountStatus;
    return this;
  }

   /**
   * Get accountStatus
   * @return accountStatus
  **/
  @ApiModelProperty(value = "")
  public ResponseTMobileIdentityAccountDetailsAccountStatus getAccountStatus() {
    return accountStatus;
  }

  public void setAccountStatus(ResponseTMobileIdentityAccountDetailsAccountStatus accountStatus) {
    this.accountStatus = accountStatus;
  }

  public ResponseTMobileIdentityAccountDetails access(ResponseTMobileIdentityAccountDetailsAccess access) {
    this.access = access;
    return this;
  }

   /**
   * Get access
   * @return access
  **/
  @ApiModelProperty(value = "")
  public ResponseTMobileIdentityAccountDetailsAccess getAccess() {
    return access;
  }

  public void setAccess(ResponseTMobileIdentityAccountDetailsAccess access) {
    this.access = access;
  }

  public ResponseTMobileIdentityAccountDetails availableLists(ResponseTMobileIdentityAccountDetailsAvailableLists availableLists) {
    this.availableLists = availableLists;
    return this;
  }

   /**
   * Get availableLists
   * @return availableLists
  **/
  @ApiModelProperty(value = "")
  public ResponseTMobileIdentityAccountDetailsAvailableLists getAvailableLists() {
    return availableLists;
  }

  public void setAvailableLists(ResponseTMobileIdentityAccountDetailsAvailableLists availableLists) {
    this.availableLists = availableLists;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseTMobileIdentityAccountDetails responseTMobileIdentityAccountDetails = (ResponseTMobileIdentityAccountDetails) o;
    return Objects.equals(this.user, responseTMobileIdentityAccountDetails.user) &&
        Objects.equals(this.authentication, responseTMobileIdentityAccountDetails.authentication) &&
        Objects.equals(this.security, responseTMobileIdentityAccountDetails.security) &&
        Objects.equals(this.passwords, responseTMobileIdentityAccountDetails.passwords) &&
        Objects.equals(this.accountStatus, responseTMobileIdentityAccountDetails.accountStatus) &&
        Objects.equals(this.access, responseTMobileIdentityAccountDetails.access) &&
        Objects.equals(this.availableLists, responseTMobileIdentityAccountDetails.availableLists);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, authentication, security, passwords, accountStatus, access, availableLists);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseTMobileIdentityAccountDetails {\n");
    
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("    security: ").append(toIndentedString(security)).append("\n");
    sb.append("    passwords: ").append(toIndentedString(passwords)).append("\n");
    sb.append("    accountStatus: ").append(toIndentedString(accountStatus)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("    availableLists: ").append(toIndentedString(availableLists)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

