/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponsePrivacyOfferDelivery
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponsePrivacyOfferDelivery {
  @SerializedName("MailDelivery")
  private Boolean mailDelivery = null;

  @SerializedName("SMSDelivery")
  private Boolean smSDelivery = null;

  @SerializedName("EMailDelivery")
  private Boolean emailDelivery = null;

  public ResponsePrivacyOfferDelivery mailDelivery(Boolean mailDelivery) {
    this.mailDelivery = mailDelivery;
    return this;
  }

   /**
   * Get mailDelivery
   * @return mailDelivery
  **/
  @ApiModelProperty(value = "")
  public Boolean getMailDelivery() {
    return mailDelivery;
  }

  public void setMailDelivery(Boolean mailDelivery) {
    this.mailDelivery = mailDelivery;
  }

  public ResponsePrivacyOfferDelivery smSDelivery(Boolean smSDelivery) {
    this.smSDelivery = smSDelivery;
    return this;
  }

   /**
   * Get smSDelivery
   * @return smSDelivery
  **/
  @ApiModelProperty(value = "")
  public Boolean getSmSDelivery() {
    return smSDelivery;
  }

  public void setSmSDelivery(Boolean smSDelivery) {
    this.smSDelivery = smSDelivery;
  }

  public ResponsePrivacyOfferDelivery emailDelivery(Boolean emailDelivery) {
    this.emailDelivery = emailDelivery;
    return this;
  }

   /**
   * Get emailDelivery
   * @return emailDelivery
  **/
  @ApiModelProperty(value = "")
  public Boolean getEmailDelivery() {
    return emailDelivery;
  }

  public void setEmailDelivery(Boolean emailDelivery) {
    this.emailDelivery = emailDelivery;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePrivacyOfferDelivery responsePrivacyOfferDelivery = (ResponsePrivacyOfferDelivery) o;
    return Objects.equals(this.mailDelivery, responsePrivacyOfferDelivery.mailDelivery) &&
        Objects.equals(this.smSDelivery, responsePrivacyOfferDelivery.smSDelivery) &&
        Objects.equals(this.emailDelivery, responsePrivacyOfferDelivery.emailDelivery);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mailDelivery, smSDelivery, emailDelivery);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePrivacyOfferDelivery {\n");
    
    sb.append("    mailDelivery: ").append(toIndentedString(mailDelivery)).append("\n");
    sb.append("    smSDelivery: ").append(toIndentedString(smSDelivery)).append("\n");
    sb.append("    emailDelivery: ").append(toIndentedString(emailDelivery)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

