/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponseTMobileIdentityAccountDetailsAccountStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseTMobileIdentityAccountDetailsAccountStatus {
  @SerializedName("Status")
  private String status = null;

  @SerializedName("AccountSoftLocked")
  private Boolean accountSoftLocked = null;

  @SerializedName("AccountSoftLockedReason")
  private String accountSoftLockedReason = null;

  @SerializedName("AccountHardLocked")
  private Boolean accountHardLocked = null;

  @SerializedName("AccountHardLockedReason")
  private String accountHardLockedReason = null;

  @SerializedName("AcccountAdminLocked")
  private Boolean acccountAdminLocked = null;

  @SerializedName("AcccountAdminLockedReason")
  private String acccountAdminLockedReason = null;

  @SerializedName("mustChangePasswordFlag")
  private Boolean mustChangePasswordFlag = null;

  @SerializedName("mustChangePasswordReason")
  private String mustChangePasswordReason = null;

  public ResponseTMobileIdentityAccountDetailsAccountStatus status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ResponseTMobileIdentityAccountDetailsAccountStatus accountSoftLocked(Boolean accountSoftLocked) {
    this.accountSoftLocked = accountSoftLocked;
    return this;
  }

   /**
   * Get accountSoftLocked
   * @return accountSoftLocked
  **/
  @ApiModelProperty(value = "")
  public Boolean getAccountSoftLocked() {
    return accountSoftLocked;
  }

  public void setAccountSoftLocked(Boolean accountSoftLocked) {
    this.accountSoftLocked = accountSoftLocked;
  }

  public ResponseTMobileIdentityAccountDetailsAccountStatus accountSoftLockedReason(String accountSoftLockedReason) {
    this.accountSoftLockedReason = accountSoftLockedReason;
    return this;
  }

   /**
   * Get accountSoftLockedReason
   * @return accountSoftLockedReason
  **/
  @ApiModelProperty(value = "")
  public String getAccountSoftLockedReason() {
    return accountSoftLockedReason;
  }

  public void setAccountSoftLockedReason(String accountSoftLockedReason) {
    this.accountSoftLockedReason = accountSoftLockedReason;
  }

  public ResponseTMobileIdentityAccountDetailsAccountStatus accountHardLocked(Boolean accountHardLocked) {
    this.accountHardLocked = accountHardLocked;
    return this;
  }

   /**
   * Get accountHardLocked
   * @return accountHardLocked
  **/
  @ApiModelProperty(value = "")
  public Boolean getAccountHardLocked() {
    return accountHardLocked;
  }

  public void setAccountHardLocked(Boolean accountHardLocked) {
    this.accountHardLocked = accountHardLocked;
  }

  public ResponseTMobileIdentityAccountDetailsAccountStatus accountHardLockedReason(String accountHardLockedReason) {
    this.accountHardLockedReason = accountHardLockedReason;
    return this;
  }

   /**
   * Get accountHardLockedReason
   * @return accountHardLockedReason
  **/
  @ApiModelProperty(value = "")
  public String getAccountHardLockedReason() {
    return accountHardLockedReason;
  }

  public void setAccountHardLockedReason(String accountHardLockedReason) {
    this.accountHardLockedReason = accountHardLockedReason;
  }

  public ResponseTMobileIdentityAccountDetailsAccountStatus acccountAdminLocked(Boolean acccountAdminLocked) {
    this.acccountAdminLocked = acccountAdminLocked;
    return this;
  }

   /**
   * Get acccountAdminLocked
   * @return acccountAdminLocked
  **/
  @ApiModelProperty(value = "")
  public Boolean getAcccountAdminLocked() {
    return acccountAdminLocked;
  }

  public void setAcccountAdminLocked(Boolean acccountAdminLocked) {
    this.acccountAdminLocked = acccountAdminLocked;
  }

  public ResponseTMobileIdentityAccountDetailsAccountStatus acccountAdminLockedReason(String acccountAdminLockedReason) {
    this.acccountAdminLockedReason = acccountAdminLockedReason;
    return this;
  }

   /**
   * Get acccountAdminLockedReason
   * @return acccountAdminLockedReason
  **/
  @ApiModelProperty(value = "")
  public String getAcccountAdminLockedReason() {
    return acccountAdminLockedReason;
  }

  public void setAcccountAdminLockedReason(String acccountAdminLockedReason) {
    this.acccountAdminLockedReason = acccountAdminLockedReason;
  }

  public ResponseTMobileIdentityAccountDetailsAccountStatus mustChangePasswordFlag(Boolean mustChangePasswordFlag) {
    this.mustChangePasswordFlag = mustChangePasswordFlag;
    return this;
  }

   /**
   * Get mustChangePasswordFlag
   * @return mustChangePasswordFlag
  **/
  @ApiModelProperty(value = "")
  public Boolean getMustChangePasswordFlag() {
    return mustChangePasswordFlag;
  }

  public void setMustChangePasswordFlag(Boolean mustChangePasswordFlag) {
    this.mustChangePasswordFlag = mustChangePasswordFlag;
  }

  public ResponseTMobileIdentityAccountDetailsAccountStatus mustChangePasswordReason(String mustChangePasswordReason) {
    this.mustChangePasswordReason = mustChangePasswordReason;
    return this;
  }

   /**
   * Get mustChangePasswordReason
   * @return mustChangePasswordReason
  **/
  @ApiModelProperty(value = "")
  public String getMustChangePasswordReason() {
    return mustChangePasswordReason;
  }

  public void setMustChangePasswordReason(String mustChangePasswordReason) {
    this.mustChangePasswordReason = mustChangePasswordReason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseTMobileIdentityAccountDetailsAccountStatus responseTMobileIdentityAccountDetailsAccountStatus = (ResponseTMobileIdentityAccountDetailsAccountStatus) o;
    return Objects.equals(this.status, responseTMobileIdentityAccountDetailsAccountStatus.status) &&
        Objects.equals(this.accountSoftLocked, responseTMobileIdentityAccountDetailsAccountStatus.accountSoftLocked) &&
        Objects.equals(this.accountSoftLockedReason, responseTMobileIdentityAccountDetailsAccountStatus.accountSoftLockedReason) &&
        Objects.equals(this.accountHardLocked, responseTMobileIdentityAccountDetailsAccountStatus.accountHardLocked) &&
        Objects.equals(this.accountHardLockedReason, responseTMobileIdentityAccountDetailsAccountStatus.accountHardLockedReason) &&
        Objects.equals(this.acccountAdminLocked, responseTMobileIdentityAccountDetailsAccountStatus.acccountAdminLocked) &&
        Objects.equals(this.acccountAdminLockedReason, responseTMobileIdentityAccountDetailsAccountStatus.acccountAdminLockedReason) &&
        Objects.equals(this.mustChangePasswordFlag, responseTMobileIdentityAccountDetailsAccountStatus.mustChangePasswordFlag) &&
        Objects.equals(this.mustChangePasswordReason, responseTMobileIdentityAccountDetailsAccountStatus.mustChangePasswordReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, accountSoftLocked, accountSoftLockedReason, accountHardLocked, accountHardLockedReason, acccountAdminLocked, acccountAdminLockedReason, mustChangePasswordFlag, mustChangePasswordReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseTMobileIdentityAccountDetailsAccountStatus {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    accountSoftLocked: ").append(toIndentedString(accountSoftLocked)).append("\n");
    sb.append("    accountSoftLockedReason: ").append(toIndentedString(accountSoftLockedReason)).append("\n");
    sb.append("    accountHardLocked: ").append(toIndentedString(accountHardLocked)).append("\n");
    sb.append("    accountHardLockedReason: ").append(toIndentedString(accountHardLockedReason)).append("\n");
    sb.append("    acccountAdminLocked: ").append(toIndentedString(acccountAdminLocked)).append("\n");
    sb.append("    acccountAdminLockedReason: ").append(toIndentedString(acccountAdminLockedReason)).append("\n");
    sb.append("    mustChangePasswordFlag: ").append(toIndentedString(mustChangePasswordFlag)).append("\n");
    sb.append("    mustChangePasswordReason: ").append(toIndentedString(mustChangePasswordReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

