/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.iam.ResponseNsmResponseErrormessages;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ResponseNsmResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseNsmResponse {
  @SerializedName("status")
  private String status = null;

  @SerializedName("responseCode")
  private String responseCode = null;

  @SerializedName("errormessages")
  private List<ResponseNsmResponseErrormessages> errormessages = null;

  public ResponseNsmResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ResponseNsmResponse responseCode(String responseCode) {
    this.responseCode = responseCode;
    return this;
  }

   /**
   * Get responseCode
   * @return responseCode
  **/
  @ApiModelProperty(value = "")
  public String getResponseCode() {
    return responseCode;
  }

  public void setResponseCode(String responseCode) {
    this.responseCode = responseCode;
  }

  public ResponseNsmResponse errormessages(List<ResponseNsmResponseErrormessages> errormessages) {
    this.errormessages = errormessages;
    return this;
  }

  public ResponseNsmResponse addErrormessagesItem(ResponseNsmResponseErrormessages errormessagesItem) {
    if (this.errormessages == null) {
      this.errormessages = new ArrayList<ResponseNsmResponseErrormessages>();
    }
    this.errormessages.add(errormessagesItem);
    return this;
  }

   /**
   * Get errormessages
   * @return errormessages
  **/
  @ApiModelProperty(value = "")
  public List<ResponseNsmResponseErrormessages> getErrormessages() {
    return errormessages;
  }

  public void setErrormessages(List<ResponseNsmResponseErrormessages> errormessages) {
    this.errormessages = errormessages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseNsmResponse responseNsmResponse = (ResponseNsmResponse) o;
    return Objects.equals(this.status, responseNsmResponse.status) &&
        Objects.equals(this.responseCode, responseNsmResponse.responseCode) &&
        Objects.equals(this.errormessages, responseNsmResponse.errormessages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, responseCode, errormessages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseNsmResponse {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    responseCode: ").append(toIndentedString(responseCode)).append("\n");
    sb.append("    errormessages: ").append(toIndentedString(errormessages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

