/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * ResponseLines
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseLines {
  @SerializedName("Line")
  private BigDecimal line = null;

  @SerializedName("msisdn")
  private String msisdn = null;

  @SerializedName("IMSI")
  private String IMSI = null;

  @SerializedName("ICCID")
  private String ICCID = null;

  @SerializedName("FirstName")
  private String firstName = null;

  @SerializedName("CustomerID")
  private String customerID = null;

  @SerializedName("SubscriberType")
  private String subscriberType = null;

  @SerializedName("CustomerType")
  private String customerType = null;

  @SerializedName("AccountType")
  private String accountType = null;

  @SerializedName("Status")
  private String status = null;

  public ResponseLines line(BigDecimal line) {
    this.line = line;
    return this;
  }

   /**
   * Get line
   * @return line
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getLine() {
    return line;
  }

  public void setLine(BigDecimal line) {
    this.line = line;
  }

  public ResponseLines msisdn(String msisdn) {
    this.msisdn = msisdn;
    return this;
  }

   /**
   * Get msisdn
   * @return msisdn
  **/
  @ApiModelProperty(value = "")
  public String getMsisdn() {
    return msisdn;
  }

  public void setMsisdn(String msisdn) {
    this.msisdn = msisdn;
  }

  public ResponseLines IMSI(String IMSI) {
    this.IMSI = IMSI;
    return this;
  }

   /**
   * Get IMSI
   * @return IMSI
  **/
  @ApiModelProperty(value = "")
  public String getIMSI() {
    return IMSI;
  }

  public void setIMSI(String IMSI) {
    this.IMSI = IMSI;
  }

  public ResponseLines ICCID(String ICCID) {
    this.ICCID = ICCID;
    return this;
  }

   /**
   * Get ICCID
   * @return ICCID
  **/
  @ApiModelProperty(value = "")
  public String getICCID() {
    return ICCID;
  }

  public void setICCID(String ICCID) {
    this.ICCID = ICCID;
  }

  public ResponseLines firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ResponseLines customerID(String customerID) {
    this.customerID = customerID;
    return this;
  }

   /**
   * Get customerID
   * @return customerID
  **/
  @ApiModelProperty(value = "")
  public String getCustomerID() {
    return customerID;
  }

  public void setCustomerID(String customerID) {
    this.customerID = customerID;
  }

  public ResponseLines subscriberType(String subscriberType) {
    this.subscriberType = subscriberType;
    return this;
  }

   /**
   * Get subscriberType
   * @return subscriberType
  **/
  @ApiModelProperty(value = "")
  public String getSubscriberType() {
    return subscriberType;
  }

  public void setSubscriberType(String subscriberType) {
    this.subscriberType = subscriberType;
  }

  public ResponseLines customerType(String customerType) {
    this.customerType = customerType;
    return this;
  }

   /**
   * Get customerType
   * @return customerType
  **/
  @ApiModelProperty(value = "")
  public String getCustomerType() {
    return customerType;
  }

  public void setCustomerType(String customerType) {
    this.customerType = customerType;
  }

  public ResponseLines accountType(String accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/
  @ApiModelProperty(value = "")
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }

  public ResponseLines status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseLines responseLines = (ResponseLines) o;
    return Objects.equals(this.line, responseLines.line) &&
        Objects.equals(this.msisdn, responseLines.msisdn) &&
        Objects.equals(this.IMSI, responseLines.IMSI) &&
        Objects.equals(this.ICCID, responseLines.ICCID) &&
        Objects.equals(this.firstName, responseLines.firstName) &&
        Objects.equals(this.customerID, responseLines.customerID) &&
        Objects.equals(this.subscriberType, responseLines.subscriberType) &&
        Objects.equals(this.customerType, responseLines.customerType) &&
        Objects.equals(this.accountType, responseLines.accountType) &&
        Objects.equals(this.status, responseLines.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(line, msisdn, IMSI, ICCID, firstName, customerID, subscriberType, customerType, accountType, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseLines {\n");
    
    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("    msisdn: ").append(toIndentedString(msisdn)).append("\n");
    sb.append("    IMSI: ").append(toIndentedString(IMSI)).append("\n");
    sb.append("    ICCID: ").append(toIndentedString(ICCID)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    customerID: ").append(toIndentedString(customerID)).append("\n");
    sb.append("    subscriberType: ").append(toIndentedString(subscriberType)).append("\n");
    sb.append("    customerType: ").append(toIndentedString(customerType)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

