/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponseIAMUniverseAccountDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseIAMUniverseAccountDetails {
  @SerializedName("Language")
  private String language = null;

  @SerializedName("FirstName")
  private String firstName = null;

  @SerializedName("LastName")
  private String lastName = null;

  @SerializedName("LastEmailUpdate")
  private String lastEmailUpdate = null;

  public ResponseIAMUniverseAccountDetails language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(value = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public ResponseIAMUniverseAccountDetails firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ResponseIAMUniverseAccountDetails lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public ResponseIAMUniverseAccountDetails lastEmailUpdate(String lastEmailUpdate) {
    this.lastEmailUpdate = lastEmailUpdate;
    return this;
  }

   /**
   * Get lastEmailUpdate
   * @return lastEmailUpdate
  **/
  @ApiModelProperty(value = "")
  public String getLastEmailUpdate() {
    return lastEmailUpdate;
  }

  public void setLastEmailUpdate(String lastEmailUpdate) {
    this.lastEmailUpdate = lastEmailUpdate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseIAMUniverseAccountDetails responseIAMUniverseAccountDetails = (ResponseIAMUniverseAccountDetails) o;
    return Objects.equals(this.language, responseIAMUniverseAccountDetails.language) &&
        Objects.equals(this.firstName, responseIAMUniverseAccountDetails.firstName) &&
        Objects.equals(this.lastName, responseIAMUniverseAccountDetails.lastName) &&
        Objects.equals(this.lastEmailUpdate, responseIAMUniverseAccountDetails.lastEmailUpdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, firstName, lastName, lastEmailUpdate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseIAMUniverseAccountDetails {\n");
    
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    lastEmailUpdate: ").append(toIndentedString(lastEmailUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

