/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ResponseTMobileIdentityAccountDetailsAvailableLists
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseTMobileIdentityAccountDetailsAvailableLists {
  @SerializedName("passwordreset")
  private List<String> passwordreset = null;

  @SerializedName("unlock")
  private List<String> unlock = null;

  @SerializedName("mustChangePasswordReason")
  private List<String> mustChangePasswordReason = null;

  public ResponseTMobileIdentityAccountDetailsAvailableLists passwordreset(List<String> passwordreset) {
    this.passwordreset = passwordreset;
    return this;
  }

  public ResponseTMobileIdentityAccountDetailsAvailableLists addPasswordresetItem(String passwordresetItem) {
    if (this.passwordreset == null) {
      this.passwordreset = new ArrayList<String>();
    }
    this.passwordreset.add(passwordresetItem);
    return this;
  }

   /**
   * Get passwordreset
   * @return passwordreset
  **/
  @ApiModelProperty(value = "")
  public List<String> getPasswordreset() {
    return passwordreset;
  }

  public void setPasswordreset(List<String> passwordreset) {
    this.passwordreset = passwordreset;
  }

  public ResponseTMobileIdentityAccountDetailsAvailableLists unlock(List<String> unlock) {
    this.unlock = unlock;
    return this;
  }

  public ResponseTMobileIdentityAccountDetailsAvailableLists addUnlockItem(String unlockItem) {
    if (this.unlock == null) {
      this.unlock = new ArrayList<String>();
    }
    this.unlock.add(unlockItem);
    return this;
  }

   /**
   * Get unlock
   * @return unlock
  **/
  @ApiModelProperty(value = "")
  public List<String> getUnlock() {
    return unlock;
  }

  public void setUnlock(List<String> unlock) {
    this.unlock = unlock;
  }

  public ResponseTMobileIdentityAccountDetailsAvailableLists mustChangePasswordReason(List<String> mustChangePasswordReason) {
    this.mustChangePasswordReason = mustChangePasswordReason;
    return this;
  }

  public ResponseTMobileIdentityAccountDetailsAvailableLists addMustChangePasswordReasonItem(String mustChangePasswordReasonItem) {
    if (this.mustChangePasswordReason == null) {
      this.mustChangePasswordReason = new ArrayList<String>();
    }
    this.mustChangePasswordReason.add(mustChangePasswordReasonItem);
    return this;
  }

   /**
   * Get mustChangePasswordReason
   * @return mustChangePasswordReason
  **/
  @ApiModelProperty(value = "")
  public List<String> getMustChangePasswordReason() {
    return mustChangePasswordReason;
  }

  public void setMustChangePasswordReason(List<String> mustChangePasswordReason) {
    this.mustChangePasswordReason = mustChangePasswordReason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseTMobileIdentityAccountDetailsAvailableLists responseTMobileIdentityAccountDetailsAvailableLists = (ResponseTMobileIdentityAccountDetailsAvailableLists) o;
    return Objects.equals(this.passwordreset, responseTMobileIdentityAccountDetailsAvailableLists.passwordreset) &&
        Objects.equals(this.unlock, responseTMobileIdentityAccountDetailsAvailableLists.unlock) &&
        Objects.equals(this.mustChangePasswordReason, responseTMobileIdentityAccountDetailsAvailableLists.mustChangePasswordReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(passwordreset, unlock, mustChangePasswordReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseTMobileIdentityAccountDetailsAvailableLists {\n");
    
    sb.append("    passwordreset: ").append(toIndentedString(passwordreset)).append("\n");
    sb.append("    unlock: ").append(toIndentedString(unlock)).append("\n");
    sb.append("    mustChangePasswordReason: ").append(toIndentedString(mustChangePasswordReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

