/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponseTMobileIdentityAccountDetailsUser
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseTMobileIdentityAccountDetailsUser {
  @SerializedName("FirstName")
  private String firstName = null;

  @SerializedName("LastName")
  private String lastName = null;

  @SerializedName("AccountCreateDate")
  private String accountCreateDate = null;

  @SerializedName("IAMLastEmailUpdate")
  private String iaMLastEmailUpdate = null;

  public ResponseTMobileIdentityAccountDetailsUser firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ResponseTMobileIdentityAccountDetailsUser lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public ResponseTMobileIdentityAccountDetailsUser accountCreateDate(String accountCreateDate) {
    this.accountCreateDate = accountCreateDate;
    return this;
  }

   /**
   * Get accountCreateDate
   * @return accountCreateDate
  **/
  @ApiModelProperty(value = "")
  public String getAccountCreateDate() {
    return accountCreateDate;
  }

  public void setAccountCreateDate(String accountCreateDate) {
    this.accountCreateDate = accountCreateDate;
  }

  public ResponseTMobileIdentityAccountDetailsUser iaMLastEmailUpdate(String iaMLastEmailUpdate) {
    this.iaMLastEmailUpdate = iaMLastEmailUpdate;
    return this;
  }

   /**
   * Get iaMLastEmailUpdate
   * @return iaMLastEmailUpdate
  **/
  @ApiModelProperty(value = "")
  public String getIaMLastEmailUpdate() {
    return iaMLastEmailUpdate;
  }

  public void setIaMLastEmailUpdate(String iaMLastEmailUpdate) {
    this.iaMLastEmailUpdate = iaMLastEmailUpdate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseTMobileIdentityAccountDetailsUser responseTMobileIdentityAccountDetailsUser = (ResponseTMobileIdentityAccountDetailsUser) o;
    return Objects.equals(this.firstName, responseTMobileIdentityAccountDetailsUser.firstName) &&
        Objects.equals(this.lastName, responseTMobileIdentityAccountDetailsUser.lastName) &&
        Objects.equals(this.accountCreateDate, responseTMobileIdentityAccountDetailsUser.accountCreateDate) &&
        Objects.equals(this.iaMLastEmailUpdate, responseTMobileIdentityAccountDetailsUser.iaMLastEmailUpdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, accountCreateDate, iaMLastEmailUpdate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseTMobileIdentityAccountDetailsUser {\n");
    
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    accountCreateDate: ").append(toIndentedString(accountCreateDate)).append("\n");
    sb.append("    iaMLastEmailUpdate: ").append(toIndentedString(iaMLastEmailUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

