/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponsePrivacyContactPreferences
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponsePrivacyContactPreferences {
  @SerializedName("EmailNewsLetter")
  private Boolean emailNewsLetter = null;

  @SerializedName("AnnualEIPDisclosure")
  private Boolean annualEIPDisclosure = null;

  public ResponsePrivacyContactPreferences emailNewsLetter(Boolean emailNewsLetter) {
    this.emailNewsLetter = emailNewsLetter;
    return this;
  }

   /**
   * Get emailNewsLetter
   * @return emailNewsLetter
  **/
  @ApiModelProperty(value = "")
  public Boolean getEmailNewsLetter() {
    return emailNewsLetter;
  }

  public void setEmailNewsLetter(Boolean emailNewsLetter) {
    this.emailNewsLetter = emailNewsLetter;
  }

  public ResponsePrivacyContactPreferences annualEIPDisclosure(Boolean annualEIPDisclosure) {
    this.annualEIPDisclosure = annualEIPDisclosure;
    return this;
  }

   /**
   * Get annualEIPDisclosure
   * @return annualEIPDisclosure
  **/
  @ApiModelProperty(value = "")
  public Boolean getAnnualEIPDisclosure() {
    return annualEIPDisclosure;
  }

  public void setAnnualEIPDisclosure(Boolean annualEIPDisclosure) {
    this.annualEIPDisclosure = annualEIPDisclosure;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePrivacyContactPreferences responsePrivacyContactPreferences = (ResponsePrivacyContactPreferences) o;
    return Objects.equals(this.emailNewsLetter, responsePrivacyContactPreferences.emailNewsLetter) &&
        Objects.equals(this.annualEIPDisclosure, responsePrivacyContactPreferences.annualEIPDisclosure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailNewsLetter, annualEIPDisclosure);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePrivacyContactPreferences {\n");
    
    sb.append("    emailNewsLetter: ").append(toIndentedString(emailNewsLetter)).append("\n");
    sb.append("    annualEIPDisclosure: ").append(toIndentedString(annualEIPDisclosure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

