/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponsePrivacyPreference
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponsePrivacyPreference {
  @SerializedName("prefid")
  private String prefid = null;

  @SerializedName("prefname")
  private String prefname = null;

  public ResponsePrivacyPreference prefid(String prefid) {
    this.prefid = prefid;
    return this;
  }

   /**
   * Get prefid
   * @return prefid
  **/
  @ApiModelProperty(value = "")
  public String getPrefid() {
    return prefid;
  }

  public void setPrefid(String prefid) {
    this.prefid = prefid;
  }

  public ResponsePrivacyPreference prefname(String prefname) {
    this.prefname = prefname;
    return this;
  }

   /**
   * Get prefname
   * @return prefname
  **/
  @ApiModelProperty(value = "")
  public String getPrefname() {
    return prefname;
  }

  public void setPrefname(String prefname) {
    this.prefname = prefname;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePrivacyPreference responsePrivacyPreference = (ResponsePrivacyPreference) o;
    return Objects.equals(this.prefid, responsePrivacyPreference.prefid) &&
        Objects.equals(this.prefname, responsePrivacyPreference.prefname);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prefid, prefname);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePrivacyPreference {\n");
    
    sb.append("    prefid: ").append(toIndentedString(prefid)).append("\n");
    sb.append("    prefname: ").append(toIndentedString(prefname)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

