/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.iam.ResponseIAMUniverseCustomerDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponseIAMUniverseCustomers
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseIAMUniverseCustomers {
  @SerializedName("CustomerDetails")
  private ResponseIAMUniverseCustomerDetails customerDetails = null;

  public ResponseIAMUniverseCustomers customerDetails(ResponseIAMUniverseCustomerDetails customerDetails) {
    this.customerDetails = customerDetails;
    return this;
  }

   /**
   * Get customerDetails
   * @return customerDetails
  **/
  @ApiModelProperty(value = "")
  public ResponseIAMUniverseCustomerDetails getCustomerDetails() {
    return customerDetails;
  }

  public void setCustomerDetails(ResponseIAMUniverseCustomerDetails customerDetails) {
    this.customerDetails = customerDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseIAMUniverseCustomers responseIAMUniverseCustomers = (ResponseIAMUniverseCustomers) o;
    return Objects.equals(this.customerDetails, responseIAMUniverseCustomers.customerDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseIAMUniverseCustomers {\n");
    
    sb.append("    customerDetails: ").append(toIndentedString(customerDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

