/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponseLinkedLinesDefaultLine
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseLinkedLinesDefaultLine {
  @SerializedName("msisdn")
  private String msisdn = null;

  @SerializedName("BAN")
  private String BAN = null;

  @SerializedName("IMSI")
  private String IMSI = null;

  @SerializedName("Operator")
  private String operator = null;

  @SerializedName("CustomerNumber")
  private String customerNumber = null;

  @SerializedName("AccountStatus")
  private String accountStatus = null;

  @SerializedName("RegistrationStatus")
  private String registrationStatus = null;

  @SerializedName("LockStatus")
  private String lockStatus = null;

  @SerializedName("LockedBy")
  private String lockedBy = null;

  @SerializedName("LockReason")
  private String lockReason = null;

  @SerializedName("DefaultLine")
  private Boolean defaultLine = null;

  @SerializedName("FirstName")
  private String firstName = null;

  @SerializedName("LastName")
  private String lastName = null;

  @SerializedName("LineID")
  private String lineID = null;

  @SerializedName("AccountType")
  private String accountType = null;

  @SerializedName("SubscriberType")
  private String subscriberType = null;

  @SerializedName("GrantMasterPrivileges")
  private String grantMasterPrivileges = null;

  @SerializedName("CustomerType")
  private String customerType = null;

  @SerializedName("Pincode")
  private String pincode = null;

  @SerializedName("SOCList")
  private String soCList = null;

  @SerializedName("ShortCodeBlacklist")
  private String shortCodeBlacklist = null;

  @SerializedName("ShortCodeBlacklistAll")
  private String shortCodeBlacklistAll = null;

  @SerializedName("MDSEnabled")
  private Boolean mdSEnabled = null;

  @SerializedName("IBAOptOut")
  private Boolean ibAOptOut = null;

  @SerializedName("MWIEnabled")
  private Boolean mwIEnabled = null;

  @SerializedName("VoWiFiEnabled")
  private Boolean voWiFiEnabled = null;

  @SerializedName("CommunicationPreference")
  private String communicationPreference = null;

  public ResponseLinkedLinesDefaultLine msisdn(String msisdn) {
    this.msisdn = msisdn;
    return this;
  }

   /**
   * Get msisdn
   * @return msisdn
  **/
  @ApiModelProperty(value = "")
  public String getMsisdn() {
    return msisdn;
  }

  public void setMsisdn(String msisdn) {
    this.msisdn = msisdn;
  }

  public ResponseLinkedLinesDefaultLine BAN(String BAN) {
    this.BAN = BAN;
    return this;
  }

   /**
   * Get BAN
   * @return BAN
  **/
  @ApiModelProperty(value = "")
  public String getBAN() {
    return BAN;
  }

  public void setBAN(String BAN) {
    this.BAN = BAN;
  }

  public ResponseLinkedLinesDefaultLine IMSI(String IMSI) {
    this.IMSI = IMSI;
    return this;
  }

   /**
   * Get IMSI
   * @return IMSI
  **/
  @ApiModelProperty(value = "")
  public String getIMSI() {
    return IMSI;
  }

  public void setIMSI(String IMSI) {
    this.IMSI = IMSI;
  }

  public ResponseLinkedLinesDefaultLine operator(String operator) {
    this.operator = operator;
    return this;
  }

   /**
   * Get operator
   * @return operator
  **/
  @ApiModelProperty(value = "")
  public String getOperator() {
    return operator;
  }

  public void setOperator(String operator) {
    this.operator = operator;
  }

  public ResponseLinkedLinesDefaultLine customerNumber(String customerNumber) {
    this.customerNumber = customerNumber;
    return this;
  }

   /**
   * Get customerNumber
   * @return customerNumber
  **/
  @ApiModelProperty(value = "")
  public String getCustomerNumber() {
    return customerNumber;
  }

  public void setCustomerNumber(String customerNumber) {
    this.customerNumber = customerNumber;
  }

  public ResponseLinkedLinesDefaultLine accountStatus(String accountStatus) {
    this.accountStatus = accountStatus;
    return this;
  }

   /**
   * Get accountStatus
   * @return accountStatus
  **/
  @ApiModelProperty(value = "")
  public String getAccountStatus() {
    return accountStatus;
  }

  public void setAccountStatus(String accountStatus) {
    this.accountStatus = accountStatus;
  }

  public ResponseLinkedLinesDefaultLine registrationStatus(String registrationStatus) {
    this.registrationStatus = registrationStatus;
    return this;
  }

   /**
   * Get registrationStatus
   * @return registrationStatus
  **/
  @ApiModelProperty(value = "")
  public String getRegistrationStatus() {
    return registrationStatus;
  }

  public void setRegistrationStatus(String registrationStatus) {
    this.registrationStatus = registrationStatus;
  }

  public ResponseLinkedLinesDefaultLine lockStatus(String lockStatus) {
    this.lockStatus = lockStatus;
    return this;
  }

   /**
   * Get lockStatus
   * @return lockStatus
  **/
  @ApiModelProperty(value = "")
  public String getLockStatus() {
    return lockStatus;
  }

  public void setLockStatus(String lockStatus) {
    this.lockStatus = lockStatus;
  }

  public ResponseLinkedLinesDefaultLine lockedBy(String lockedBy) {
    this.lockedBy = lockedBy;
    return this;
  }

   /**
   * Get lockedBy
   * @return lockedBy
  **/
  @ApiModelProperty(value = "")
  public String getLockedBy() {
    return lockedBy;
  }

  public void setLockedBy(String lockedBy) {
    this.lockedBy = lockedBy;
  }

  public ResponseLinkedLinesDefaultLine lockReason(String lockReason) {
    this.lockReason = lockReason;
    return this;
  }

   /**
   * Get lockReason
   * @return lockReason
  **/
  @ApiModelProperty(value = "")
  public String getLockReason() {
    return lockReason;
  }

  public void setLockReason(String lockReason) {
    this.lockReason = lockReason;
  }

  public ResponseLinkedLinesDefaultLine defaultLine(Boolean defaultLine) {
    this.defaultLine = defaultLine;
    return this;
  }

   /**
   * Get defaultLine
   * @return defaultLine
  **/
  @ApiModelProperty(value = "")
  public Boolean getDefaultLine() {
    return defaultLine;
  }

  public void setDefaultLine(Boolean defaultLine) {
    this.defaultLine = defaultLine;
  }

  public ResponseLinkedLinesDefaultLine firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ResponseLinkedLinesDefaultLine lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public ResponseLinkedLinesDefaultLine lineID(String lineID) {
    this.lineID = lineID;
    return this;
  }

   /**
   * Get lineID
   * @return lineID
  **/
  @ApiModelProperty(value = "")
  public String getLineID() {
    return lineID;
  }

  public void setLineID(String lineID) {
    this.lineID = lineID;
  }

  public ResponseLinkedLinesDefaultLine accountType(String accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/
  @ApiModelProperty(value = "")
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }

  public ResponseLinkedLinesDefaultLine subscriberType(String subscriberType) {
    this.subscriberType = subscriberType;
    return this;
  }

   /**
   * Get subscriberType
   * @return subscriberType
  **/
  @ApiModelProperty(value = "")
  public String getSubscriberType() {
    return subscriberType;
  }

  public void setSubscriberType(String subscriberType) {
    this.subscriberType = subscriberType;
  }

  public ResponseLinkedLinesDefaultLine grantMasterPrivileges(String grantMasterPrivileges) {
    this.grantMasterPrivileges = grantMasterPrivileges;
    return this;
  }

   /**
   * Get grantMasterPrivileges
   * @return grantMasterPrivileges
  **/
  @ApiModelProperty(value = "")
  public String getGrantMasterPrivileges() {
    return grantMasterPrivileges;
  }

  public void setGrantMasterPrivileges(String grantMasterPrivileges) {
    this.grantMasterPrivileges = grantMasterPrivileges;
  }

  public ResponseLinkedLinesDefaultLine customerType(String customerType) {
    this.customerType = customerType;
    return this;
  }

   /**
   * Get customerType
   * @return customerType
  **/
  @ApiModelProperty(value = "")
  public String getCustomerType() {
    return customerType;
  }

  public void setCustomerType(String customerType) {
    this.customerType = customerType;
  }

  public ResponseLinkedLinesDefaultLine pincode(String pincode) {
    this.pincode = pincode;
    return this;
  }

   /**
   * Get pincode
   * @return pincode
  **/
  @ApiModelProperty(value = "")
  public String getPincode() {
    return pincode;
  }

  public void setPincode(String pincode) {
    this.pincode = pincode;
  }

  public ResponseLinkedLinesDefaultLine soCList(String soCList) {
    this.soCList = soCList;
    return this;
  }

   /**
   * Get soCList
   * @return soCList
  **/
  @ApiModelProperty(value = "")
  public String getSoCList() {
    return soCList;
  }

  public void setSoCList(String soCList) {
    this.soCList = soCList;
  }

  public ResponseLinkedLinesDefaultLine shortCodeBlacklist(String shortCodeBlacklist) {
    this.shortCodeBlacklist = shortCodeBlacklist;
    return this;
  }

   /**
   * Get shortCodeBlacklist
   * @return shortCodeBlacklist
  **/
  @ApiModelProperty(value = "")
  public String getShortCodeBlacklist() {
    return shortCodeBlacklist;
  }

  public void setShortCodeBlacklist(String shortCodeBlacklist) {
    this.shortCodeBlacklist = shortCodeBlacklist;
  }

  public ResponseLinkedLinesDefaultLine shortCodeBlacklistAll(String shortCodeBlacklistAll) {
    this.shortCodeBlacklistAll = shortCodeBlacklistAll;
    return this;
  }

   /**
   * Get shortCodeBlacklistAll
   * @return shortCodeBlacklistAll
  **/
  @ApiModelProperty(value = "")
  public String getShortCodeBlacklistAll() {
    return shortCodeBlacklistAll;
  }

  public void setShortCodeBlacklistAll(String shortCodeBlacklistAll) {
    this.shortCodeBlacklistAll = shortCodeBlacklistAll;
  }

  public ResponseLinkedLinesDefaultLine mdSEnabled(Boolean mdSEnabled) {
    this.mdSEnabled = mdSEnabled;
    return this;
  }

   /**
   * Get mdSEnabled
   * @return mdSEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean getMdSEnabled() {
    return mdSEnabled;
  }

  public void setMdSEnabled(Boolean mdSEnabled) {
    this.mdSEnabled = mdSEnabled;
  }

  public ResponseLinkedLinesDefaultLine ibAOptOut(Boolean ibAOptOut) {
    this.ibAOptOut = ibAOptOut;
    return this;
  }

   /**
   * Get ibAOptOut
   * @return ibAOptOut
  **/
  @ApiModelProperty(value = "")
  public Boolean getIbAOptOut() {
    return ibAOptOut;
  }

  public void setIbAOptOut(Boolean ibAOptOut) {
    this.ibAOptOut = ibAOptOut;
  }

  public ResponseLinkedLinesDefaultLine mwIEnabled(Boolean mwIEnabled) {
    this.mwIEnabled = mwIEnabled;
    return this;
  }

   /**
   * Get mwIEnabled
   * @return mwIEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean getMwIEnabled() {
    return mwIEnabled;
  }

  public void setMwIEnabled(Boolean mwIEnabled) {
    this.mwIEnabled = mwIEnabled;
  }

  public ResponseLinkedLinesDefaultLine voWiFiEnabled(Boolean voWiFiEnabled) {
    this.voWiFiEnabled = voWiFiEnabled;
    return this;
  }

   /**
   * Get voWiFiEnabled
   * @return voWiFiEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean getVoWiFiEnabled() {
    return voWiFiEnabled;
  }

  public void setVoWiFiEnabled(Boolean voWiFiEnabled) {
    this.voWiFiEnabled = voWiFiEnabled;
  }

  public ResponseLinkedLinesDefaultLine communicationPreference(String communicationPreference) {
    this.communicationPreference = communicationPreference;
    return this;
  }

   /**
   * Get communicationPreference
   * @return communicationPreference
  **/
  @ApiModelProperty(value = "")
  public String getCommunicationPreference() {
    return communicationPreference;
  }

  public void setCommunicationPreference(String communicationPreference) {
    this.communicationPreference = communicationPreference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseLinkedLinesDefaultLine responseLinkedLinesDefaultLine = (ResponseLinkedLinesDefaultLine) o;
    return Objects.equals(this.msisdn, responseLinkedLinesDefaultLine.msisdn) &&
        Objects.equals(this.BAN, responseLinkedLinesDefaultLine.BAN) &&
        Objects.equals(this.IMSI, responseLinkedLinesDefaultLine.IMSI) &&
        Objects.equals(this.operator, responseLinkedLinesDefaultLine.operator) &&
        Objects.equals(this.customerNumber, responseLinkedLinesDefaultLine.customerNumber) &&
        Objects.equals(this.accountStatus, responseLinkedLinesDefaultLine.accountStatus) &&
        Objects.equals(this.registrationStatus, responseLinkedLinesDefaultLine.registrationStatus) &&
        Objects.equals(this.lockStatus, responseLinkedLinesDefaultLine.lockStatus) &&
        Objects.equals(this.lockedBy, responseLinkedLinesDefaultLine.lockedBy) &&
        Objects.equals(this.lockReason, responseLinkedLinesDefaultLine.lockReason) &&
        Objects.equals(this.defaultLine, responseLinkedLinesDefaultLine.defaultLine) &&
        Objects.equals(this.firstName, responseLinkedLinesDefaultLine.firstName) &&
        Objects.equals(this.lastName, responseLinkedLinesDefaultLine.lastName) &&
        Objects.equals(this.lineID, responseLinkedLinesDefaultLine.lineID) &&
        Objects.equals(this.accountType, responseLinkedLinesDefaultLine.accountType) &&
        Objects.equals(this.subscriberType, responseLinkedLinesDefaultLine.subscriberType) &&
        Objects.equals(this.grantMasterPrivileges, responseLinkedLinesDefaultLine.grantMasterPrivileges) &&
        Objects.equals(this.customerType, responseLinkedLinesDefaultLine.customerType) &&
        Objects.equals(this.pincode, responseLinkedLinesDefaultLine.pincode) &&
        Objects.equals(this.soCList, responseLinkedLinesDefaultLine.soCList) &&
        Objects.equals(this.shortCodeBlacklist, responseLinkedLinesDefaultLine.shortCodeBlacklist) &&
        Objects.equals(this.shortCodeBlacklistAll, responseLinkedLinesDefaultLine.shortCodeBlacklistAll) &&
        Objects.equals(this.mdSEnabled, responseLinkedLinesDefaultLine.mdSEnabled) &&
        Objects.equals(this.ibAOptOut, responseLinkedLinesDefaultLine.ibAOptOut) &&
        Objects.equals(this.mwIEnabled, responseLinkedLinesDefaultLine.mwIEnabled) &&
        Objects.equals(this.voWiFiEnabled, responseLinkedLinesDefaultLine.voWiFiEnabled) &&
        Objects.equals(this.communicationPreference, responseLinkedLinesDefaultLine.communicationPreference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(msisdn, BAN, IMSI, operator, customerNumber, accountStatus, registrationStatus, lockStatus, lockedBy, lockReason, defaultLine, firstName, lastName, lineID, accountType, subscriberType, grantMasterPrivileges, customerType, pincode, soCList, shortCodeBlacklist, shortCodeBlacklistAll, mdSEnabled, ibAOptOut, mwIEnabled, voWiFiEnabled, communicationPreference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseLinkedLinesDefaultLine {\n");
    
    sb.append("    msisdn: ").append(toIndentedString(msisdn)).append("\n");
    sb.append("    BAN: ").append(toIndentedString(BAN)).append("\n");
    sb.append("    IMSI: ").append(toIndentedString(IMSI)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    customerNumber: ").append(toIndentedString(customerNumber)).append("\n");
    sb.append("    accountStatus: ").append(toIndentedString(accountStatus)).append("\n");
    sb.append("    registrationStatus: ").append(toIndentedString(registrationStatus)).append("\n");
    sb.append("    lockStatus: ").append(toIndentedString(lockStatus)).append("\n");
    sb.append("    lockedBy: ").append(toIndentedString(lockedBy)).append("\n");
    sb.append("    lockReason: ").append(toIndentedString(lockReason)).append("\n");
    sb.append("    defaultLine: ").append(toIndentedString(defaultLine)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    lineID: ").append(toIndentedString(lineID)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    subscriberType: ").append(toIndentedString(subscriberType)).append("\n");
    sb.append("    grantMasterPrivileges: ").append(toIndentedString(grantMasterPrivileges)).append("\n");
    sb.append("    customerType: ").append(toIndentedString(customerType)).append("\n");
    sb.append("    pincode: ").append(toIndentedString(pincode)).append("\n");
    sb.append("    soCList: ").append(toIndentedString(soCList)).append("\n");
    sb.append("    shortCodeBlacklist: ").append(toIndentedString(shortCodeBlacklist)).append("\n");
    sb.append("    shortCodeBlacklistAll: ").append(toIndentedString(shortCodeBlacklistAll)).append("\n");
    sb.append("    mdSEnabled: ").append(toIndentedString(mdSEnabled)).append("\n");
    sb.append("    ibAOptOut: ").append(toIndentedString(ibAOptOut)).append("\n");
    sb.append("    mwIEnabled: ").append(toIndentedString(mwIEnabled)).append("\n");
    sb.append("    voWiFiEnabled: ").append(toIndentedString(voWiFiEnabled)).append("\n");
    sb.append("    communicationPreference: ").append(toIndentedString(communicationPreference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

