/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.iam.ResponsePrivacyPreference;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ResponsePrivacyOfferPreference
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponsePrivacyOfferPreference {
  @SerializedName("offerid")
  private String offerid = null;

  @SerializedName("offer_name")
  @JsonProperty("offer_name")
  private String offerName = null;

  @SerializedName("preference")
  private List<ResponsePrivacyPreference> preference = null;

  public ResponsePrivacyOfferPreference offerid(String offerid) {
    this.offerid = offerid;
    return this;
  }

   /**
   * Get offerid
   * @return offerid
  **/
  @ApiModelProperty(value = "")
  public String getOfferid() {
    return offerid;
  }

  public void setOfferid(String offerid) {
    this.offerid = offerid;
  }

  public ResponsePrivacyOfferPreference offerName(String offerName) {
    this.offerName = offerName;
    return this;
  }

   /**
   * Get offerName
   * @return offerName
  **/
  @ApiModelProperty(value = "")
  public String getOfferName() {
    return offerName;
  }

  public void setOfferName(String offerName) {
    this.offerName = offerName;
  }

  public ResponsePrivacyOfferPreference preference(List<ResponsePrivacyPreference> preference) {
    this.preference = preference;
    return this;
  }

  public ResponsePrivacyOfferPreference addPreferenceItem(ResponsePrivacyPreference preferenceItem) {
    if (this.preference == null) {
      this.preference = new ArrayList<ResponsePrivacyPreference>();
    }
    this.preference.add(preferenceItem);
    return this;
  }

   /**
   * Get preference
   * @return preference
  **/
  @ApiModelProperty(value = "")
  public List<ResponsePrivacyPreference> getPreference() {
    return preference;
  }

  public void setPreference(List<ResponsePrivacyPreference> preference) {
    this.preference = preference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsePrivacyOfferPreference responsePrivacyOfferPreference = (ResponsePrivacyOfferPreference) o;
    return Objects.equals(this.offerid, responsePrivacyOfferPreference.offerid) &&
        Objects.equals(this.offerName, responsePrivacyOfferPreference.offerName) &&
        Objects.equals(this.preference, responsePrivacyOfferPreference.preference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offerid, offerName, preference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsePrivacyOfferPreference {\n");
    
    sb.append("    offerid: ").append(toIndentedString(offerid)).append("\n");
    sb.append("    offerName: ").append(toIndentedString(offerName)).append("\n");
    sb.append("    preference: ").append(toIndentedString(preference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

