/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponseTMobileIdentityAccountDetailsSecurity
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseTMobileIdentityAccountDetailsSecurity {
  @SerializedName("SecurityAnswerCount")
  private String securityAnswerCount = null;

  @SerializedName("SecurityAnswerUpdateDate")
  private String securityAnswerUpdateDate = null;

  public ResponseTMobileIdentityAccountDetailsSecurity securityAnswerCount(String securityAnswerCount) {
    this.securityAnswerCount = securityAnswerCount;
    return this;
  }

   /**
   * Get securityAnswerCount
   * @return securityAnswerCount
  **/
  @ApiModelProperty(value = "")
  public String getSecurityAnswerCount() {
    return securityAnswerCount;
  }

  public void setSecurityAnswerCount(String securityAnswerCount) {
    this.securityAnswerCount = securityAnswerCount;
  }

  public ResponseTMobileIdentityAccountDetailsSecurity securityAnswerUpdateDate(String securityAnswerUpdateDate) {
    this.securityAnswerUpdateDate = securityAnswerUpdateDate;
    return this;
  }

   /**
   * Get securityAnswerUpdateDate
   * @return securityAnswerUpdateDate
  **/
  @ApiModelProperty(value = "")
  public String getSecurityAnswerUpdateDate() {
    return securityAnswerUpdateDate;
  }

  public void setSecurityAnswerUpdateDate(String securityAnswerUpdateDate) {
    this.securityAnswerUpdateDate = securityAnswerUpdateDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseTMobileIdentityAccountDetailsSecurity responseTMobileIdentityAccountDetailsSecurity = (ResponseTMobileIdentityAccountDetailsSecurity) o;
    return Objects.equals(this.securityAnswerCount, responseTMobileIdentityAccountDetailsSecurity.securityAnswerCount) &&
        Objects.equals(this.securityAnswerUpdateDate, responseTMobileIdentityAccountDetailsSecurity.securityAnswerUpdateDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(securityAnswerCount, securityAnswerUpdateDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseTMobileIdentityAccountDetailsSecurity {\n");
    
    sb.append("    securityAnswerCount: ").append(toIndentedString(securityAnswerCount)).append("\n");
    sb.append("    securityAnswerUpdateDate: ").append(toIndentedString(securityAnswerUpdateDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

