/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponseIAMUniverseAccountStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseIAMUniverseAccountStatus {
  @SerializedName("Status")
  private String status = null;

  @SerializedName("AccountCreateDate")
  private String accountCreateDate = null;

  @SerializedName("LockReason")
  private String lockReason = null;

  @SerializedName("LockTimestamp")
  private String lockTimestamp = null;

  public ResponseIAMUniverseAccountStatus status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ResponseIAMUniverseAccountStatus accountCreateDate(String accountCreateDate) {
    this.accountCreateDate = accountCreateDate;
    return this;
  }

   /**
   * Get accountCreateDate
   * @return accountCreateDate
  **/
  @ApiModelProperty(value = "")
  public String getAccountCreateDate() {
    return accountCreateDate;
  }

  public void setAccountCreateDate(String accountCreateDate) {
    this.accountCreateDate = accountCreateDate;
  }

  public ResponseIAMUniverseAccountStatus lockReason(String lockReason) {
    this.lockReason = lockReason;
    return this;
  }

   /**
   * Get lockReason
   * @return lockReason
  **/
  @ApiModelProperty(value = "")
  public String getLockReason() {
    return lockReason;
  }

  public void setLockReason(String lockReason) {
    this.lockReason = lockReason;
  }

  public ResponseIAMUniverseAccountStatus lockTimestamp(String lockTimestamp) {
    this.lockTimestamp = lockTimestamp;
    return this;
  }

   /**
   * Get lockTimestamp
   * @return lockTimestamp
  **/
  @ApiModelProperty(value = "")
  public String getLockTimestamp() {
    return lockTimestamp;
  }

  public void setLockTimestamp(String lockTimestamp) {
    this.lockTimestamp = lockTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseIAMUniverseAccountStatus responseIAMUniverseAccountStatus = (ResponseIAMUniverseAccountStatus) o;
    return Objects.equals(this.status, responseIAMUniverseAccountStatus.status) &&
        Objects.equals(this.accountCreateDate, responseIAMUniverseAccountStatus.accountCreateDate) &&
        Objects.equals(this.lockReason, responseIAMUniverseAccountStatus.lockReason) &&
        Objects.equals(this.lockTimestamp, responseIAMUniverseAccountStatus.lockTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, accountCreateDate, lockReason, lockTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseIAMUniverseAccountStatus {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    accountCreateDate: ").append(toIndentedString(accountCreateDate)).append("\n");
    sb.append("    lockReason: ").append(toIndentedString(lockReason)).append("\n");
    sb.append("    lockTimestamp: ").append(toIndentedString(lockTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

