/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.iam;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResponseTMobileIdentityAccountDetailsAuthentication
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-04T13:48:26.690-05:00")
public class ResponseTMobileIdentityAccountDetailsAuthentication {
  @SerializedName("SuccessCount")
  private String successCount = null;

  @SerializedName("LastSuccessfulDate")
  private String lastSuccessfulDate = null;

  @SerializedName("FailureCount")
  private String failureCount = null;

  @SerializedName("LastfailedDate")
  private String lastfailedDate = null;

  public ResponseTMobileIdentityAccountDetailsAuthentication successCount(String successCount) {
    this.successCount = successCount;
    return this;
  }

   /**
   * Get successCount
   * @return successCount
  **/
  @ApiModelProperty(value = "")
  public String getSuccessCount() {
    return successCount;
  }

  public void setSuccessCount(String successCount) {
    this.successCount = successCount;
  }

  public ResponseTMobileIdentityAccountDetailsAuthentication lastSuccessfulDate(String lastSuccessfulDate) {
    this.lastSuccessfulDate = lastSuccessfulDate;
    return this;
  }

   /**
   * Get lastSuccessfulDate
   * @return lastSuccessfulDate
  **/
  @ApiModelProperty(value = "")
  public String getLastSuccessfulDate() {
    return lastSuccessfulDate;
  }

  public void setLastSuccessfulDate(String lastSuccessfulDate) {
    this.lastSuccessfulDate = lastSuccessfulDate;
  }

  public ResponseTMobileIdentityAccountDetailsAuthentication failureCount(String failureCount) {
    this.failureCount = failureCount;
    return this;
  }

   /**
   * Get failureCount
   * @return failureCount
  **/
  @ApiModelProperty(value = "")
  public String getFailureCount() {
    return failureCount;
  }

  public void setFailureCount(String failureCount) {
    this.failureCount = failureCount;
  }

  public ResponseTMobileIdentityAccountDetailsAuthentication lastfailedDate(String lastfailedDate) {
    this.lastfailedDate = lastfailedDate;
    return this;
  }

   /**
   * Get lastfailedDate
   * @return lastfailedDate
  **/
  @ApiModelProperty(value = "")
  public String getLastfailedDate() {
    return lastfailedDate;
  }

  public void setLastfailedDate(String lastfailedDate) {
    this.lastfailedDate = lastfailedDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseTMobileIdentityAccountDetailsAuthentication responseTMobileIdentityAccountDetailsAuthentication = (ResponseTMobileIdentityAccountDetailsAuthentication) o;
    return Objects.equals(this.successCount, responseTMobileIdentityAccountDetailsAuthentication.successCount) &&
        Objects.equals(this.lastSuccessfulDate, responseTMobileIdentityAccountDetailsAuthentication.lastSuccessfulDate) &&
        Objects.equals(this.failureCount, responseTMobileIdentityAccountDetailsAuthentication.failureCount) &&
        Objects.equals(this.lastfailedDate, responseTMobileIdentityAccountDetailsAuthentication.lastfailedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successCount, lastSuccessfulDate, failureCount, lastfailedDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseTMobileIdentityAccountDetailsAuthentication {\n");
    
    sb.append("    successCount: ").append(toIndentedString(successCount)).append("\n");
    sb.append("    lastSuccessfulDate: ").append(toIndentedString(lastSuccessfulDate)).append("\n");
    sb.append("    failureCount: ").append(toIndentedString(failureCount)).append("\n");
    sb.append("    lastfailedDate: ").append(toIndentedString(lastfailedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

