/*
 * BillingAccountsSearch
 * This service returns an account used for billing purposes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: shay.soifer@amdocs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.subscriber;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.subscriber.AccountBalance;
import com.tmobile.finance.subscriber.AccountType;
import com.tmobile.finance.subscriber.BillInfo;
import com.tmobile.finance.subscriber.BillStructure;
import com.tmobile.finance.subscriber.BillingAccountStatus;
import com.tmobile.finance.subscriber.BillingMethod;
import com.tmobile.finance.subscriber.CollectionStatus;
import com.tmobile.finance.subscriber.CreditClass;
import com.tmobile.finance.subscriber.Error;
import com.tmobile.finance.subscriber.IdRef;
import com.tmobile.finance.subscriber.LastActivity;
import com.tmobile.finance.subscriber.Organization;
import com.tmobile.finance.subscriber.Phone;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * BillingAccount
 */
@ApiModel(description = "BillingAccount")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-08T11:56:47.701-05:00")
public class BillingAccount {
  @SerializedName("_links")
  private List<IdRef> links = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("accountType")
  private AccountType accountType = null;

  @SerializedName("billInfo")
  private BillInfo billInfo = null;

  @SerializedName("activationDate")
  private Date activationDate = null;

  @SerializedName("balance")
  private AccountBalance balance = null;

  @SerializedName("billStructure")
  private BillStructure billStructure = null;

  @SerializedName("billingMethod")
  private BillingMethod billingMethod = null;

  @SerializedName("collectionStatus")
  private CollectionStatus collectionStatus = null;

  @SerializedName("collectionStatusDate")
  private Date collectionStatusDate = null;

  @SerializedName("creditClass")
  private CreditClass creditClass = null;

  @SerializedName("currentBillSequence")
  private Long currentBillSequence = null;

  @SerializedName("nextOrganization")
  private Organization nextOrganization = null;

  @SerializedName("organization")
  private Organization organization = null;

  @SerializedName("phone")
  private Phone phone = null;

  @SerializedName("status")
  private BillingAccountStatus status = null;

  @SerializedName("lastActivity")
  private LastActivity lastActivity = null;

  @SerializedName("tax")
  private String tax = null;

  @SerializedName("errorsList")
  private List<Error> errorsList = null;

  public BillingAccount links(List<IdRef> links) {
    this.links = links;
    return this;
  }

  public BillingAccount addLinksItem(IdRef linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<IdRef>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * includes HATEOAS mappings to things like organization and next-organization
   * @return links
  **/
  @ApiModelProperty(value = "includes HATEOAS mappings to things like organization and next-organization")
  public List<IdRef> getLinks() {
    return links;
  }

  public void setLinks(List<IdRef> links) {
    this.links = links;
  }

  public BillingAccount id(String id) {
    this.id = id;
    return this;
  }

   /**
   * id
   * @return id
  **/
  @ApiModelProperty(value = "id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BillingAccount accountType(AccountType accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/
  @ApiModelProperty(value = "")
  public AccountType getAccountType() {
    return accountType;
  }

  public void setAccountType(AccountType accountType) {
    this.accountType = accountType;
  }

  public BillingAccount billInfo(BillInfo billInfo) {
    this.billInfo = billInfo;
    return this;
  }

   /**
   * Get billInfo
   * @return billInfo
  **/
  @ApiModelProperty(value = "")
  public BillInfo getBillInfo() {
    return billInfo;
  }

  public void setBillInfo(BillInfo billInfo) {
    this.billInfo = billInfo;
  }

  public BillingAccount activationDate(Date activationDate) {
    this.activationDate = activationDate;
    return this;
  }

   /**
   * activationDate
   * @return activationDate
  **/
  @ApiModelProperty(value = "activationDate")
  public Date getActivationDate() {
    return activationDate;
  }

  public void setActivationDate(Date activationDate) {
    this.activationDate = activationDate;
  }

  public BillingAccount balance(AccountBalance balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Get balance
   * @return balance
  **/
  @ApiModelProperty(value = "")
  public AccountBalance getBalance() {
    return balance;
  }

  public void setBalance(AccountBalance balance) {
    this.balance = balance;
  }

  public BillingAccount billStructure(BillStructure billStructure) {
    this.billStructure = billStructure;
    return this;
  }

   /**
   * Get billStructure
   * @return billStructure
  **/
  @ApiModelProperty(value = "")
  public BillStructure getBillStructure() {
    return billStructure;
  }

  public void setBillStructure(BillStructure billStructure) {
    this.billStructure = billStructure;
  }

  public BillingAccount billingMethod(BillingMethod billingMethod) {
    this.billingMethod = billingMethod;
    return this;
  }

   /**
   * Get billingMethod
   * @return billingMethod
  **/
  @ApiModelProperty(value = "")
  public BillingMethod getBillingMethod() {
    return billingMethod;
  }

  public void setBillingMethod(BillingMethod billingMethod) {
    this.billingMethod = billingMethod;
  }

  public BillingAccount collectionStatus(CollectionStatus collectionStatus) {
    this.collectionStatus = collectionStatus;
    return this;
  }

   /**
   * Get collectionStatus
   * @return collectionStatus
  **/
  @ApiModelProperty(value = "")
  public CollectionStatus getCollectionStatus() {
    return collectionStatus;
  }

  public void setCollectionStatus(CollectionStatus collectionStatus) {
    this.collectionStatus = collectionStatus;
  }

  public BillingAccount collectionStatusDate(Date collectionStatusDate) {
    this.collectionStatusDate = collectionStatusDate;
    return this;
  }

   /**
   * collectionStatusDate
   * @return collectionStatusDate
  **/
  @ApiModelProperty(value = "collectionStatusDate")
  public Date getCollectionStatusDate() {
    return collectionStatusDate;
  }

  public void setCollectionStatusDate(Date collectionStatusDate) {
    this.collectionStatusDate = collectionStatusDate;
  }

  public BillingAccount creditClass(CreditClass creditClass) {
    this.creditClass = creditClass;
    return this;
  }

   /**
   * Get creditClass
   * @return creditClass
  **/
  @ApiModelProperty(value = "")
  public CreditClass getCreditClass() {
    return creditClass;
  }

  public void setCreditClass(CreditClass creditClass) {
    this.creditClass = creditClass;
  }

  public BillingAccount currentBillSequence(Long currentBillSequence) {
    this.currentBillSequence = currentBillSequence;
    return this;
  }

   /**
   * currentBillSequence
   * @return currentBillSequence
  **/
  @ApiModelProperty(value = "currentBillSequence")
  public Long getCurrentBillSequence() {
    return currentBillSequence;
  }

  public void setCurrentBillSequence(Long currentBillSequence) {
    this.currentBillSequence = currentBillSequence;
  }

  public BillingAccount nextOrganization(Organization nextOrganization) {
    this.nextOrganization = nextOrganization;
    return this;
  }

   /**
   * Get nextOrganization
   * @return nextOrganization
  **/
  @ApiModelProperty(value = "")
  public Organization getNextOrganization() {
    return nextOrganization;
  }

  public void setNextOrganization(Organization nextOrganization) {
    this.nextOrganization = nextOrganization;
  }

  public BillingAccount organization(Organization organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @ApiModelProperty(value = "")
  public Organization getOrganization() {
    return organization;
  }

  public void setOrganization(Organization organization) {
    this.organization = organization;
  }

  public BillingAccount phone(Phone phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(value = "")
  public Phone getPhone() {
    return phone;
  }

  public void setPhone(Phone phone) {
    this.phone = phone;
  }

  public BillingAccount status(BillingAccountStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public BillingAccountStatus getStatus() {
    return status;
  }

  public void setStatus(BillingAccountStatus status) {
    this.status = status;
  }

  public BillingAccount lastActivity(LastActivity lastActivity) {
    this.lastActivity = lastActivity;
    return this;
  }

   /**
   * Get lastActivity
   * @return lastActivity
  **/
  @ApiModelProperty(value = "")
  public LastActivity getLastActivity() {
    return lastActivity;
  }

  public void setLastActivity(LastActivity lastActivity) {
    this.lastActivity = lastActivity;
  }

  public BillingAccount tax(String tax) {
    this.tax = tax;
    return this;
  }

   /**
   * tax
   * @return tax
  **/
  @ApiModelProperty(value = "tax")
  public String getTax() {
    return tax;
  }

  public void setTax(String tax) {
    this.tax = tax;
  }

  public BillingAccount errorsList(List<Error> errorsList) {
    this.errorsList = errorsList;
    return this;
  }

  public BillingAccount addErrorsListItem(Error errorsListItem) {
    if (this.errorsList == null) {
      this.errorsList = new ArrayList<Error>();
    }
    this.errorsList.add(errorsListItem);
    return this;
  }

   /**
   * Get errorsList
   * @return errorsList
  **/
  @ApiModelProperty(value = "")
  public List<Error> getErrorsList() {
    return errorsList;
  }

  public void setErrorsList(List<Error> errorsList) {
    this.errorsList = errorsList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingAccount billingAccount = (BillingAccount) o;
    return Objects.equals(this.links, billingAccount.links) &&
        Objects.equals(this.id, billingAccount.id) &&
        Objects.equals(this.accountType, billingAccount.accountType) &&
        Objects.equals(this.billInfo, billingAccount.billInfo) &&
        Objects.equals(this.activationDate, billingAccount.activationDate) &&
        Objects.equals(this.balance, billingAccount.balance) &&
        Objects.equals(this.billStructure, billingAccount.billStructure) &&
        Objects.equals(this.billingMethod, billingAccount.billingMethod) &&
        Objects.equals(this.collectionStatus, billingAccount.collectionStatus) &&
        Objects.equals(this.collectionStatusDate, billingAccount.collectionStatusDate) &&
        Objects.equals(this.creditClass, billingAccount.creditClass) &&
        Objects.equals(this.currentBillSequence, billingAccount.currentBillSequence) &&
        Objects.equals(this.nextOrganization, billingAccount.nextOrganization) &&
        Objects.equals(this.organization, billingAccount.organization) &&
        Objects.equals(this.phone, billingAccount.phone) &&
        Objects.equals(this.status, billingAccount.status) &&
        Objects.equals(this.lastActivity, billingAccount.lastActivity) &&
        Objects.equals(this.tax, billingAccount.tax) &&
        Objects.equals(this.errorsList, billingAccount.errorsList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, id, accountType, billInfo, activationDate, balance, billStructure, billingMethod, collectionStatus, collectionStatusDate, creditClass, currentBillSequence, nextOrganization, organization, phone, status, lastActivity, tax, errorsList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingAccount {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    billInfo: ").append(toIndentedString(billInfo)).append("\n");
    sb.append("    activationDate: ").append(toIndentedString(activationDate)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    billStructure: ").append(toIndentedString(billStructure)).append("\n");
    sb.append("    billingMethod: ").append(toIndentedString(billingMethod)).append("\n");
    sb.append("    collectionStatus: ").append(toIndentedString(collectionStatus)).append("\n");
    sb.append("    collectionStatusDate: ").append(toIndentedString(collectionStatusDate)).append("\n");
    sb.append("    creditClass: ").append(toIndentedString(creditClass)).append("\n");
    sb.append("    currentBillSequence: ").append(toIndentedString(currentBillSequence)).append("\n");
    sb.append("    nextOrganization: ").append(toIndentedString(nextOrganization)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    lastActivity: ").append(toIndentedString(lastActivity)).append("\n");
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("    errorsList: ").append(toIndentedString(errorsList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

