/*
 * BillingAccountsSearch
 * This service returns an account used for billing purposes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: shay.soifer@amdocs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.subscriber;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BillingAccountStatus
 */
@ApiModel(description = "BillingAccountStatus")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-08T11:56:47.701-05:00")
public class BillingAccountStatus {
  @SerializedName("code")
  private String code = null;

  @SerializedName("accountStatusDescription")
  private String accountStatusDescription = null;

  @SerializedName("name")
  private String name = null;

  public BillingAccountStatus code(String code) {
    this.code = code;
    return this;
  }

   /**
   * code
   * @return code
  **/
  @ApiModelProperty(value = "code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public BillingAccountStatus accountStatusDescription(String accountStatusDescription) {
    this.accountStatusDescription = accountStatusDescription;
    return this;
  }

   /**
   * description
   * @return accountStatusDescription
  **/
  @ApiModelProperty(value = "description")
  public String getAccountStatusDescription() {
    return accountStatusDescription;
  }

  public void setAccountStatusDescription(String accountStatusDescription) {
    this.accountStatusDescription = accountStatusDescription;
  }

  public BillingAccountStatus name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name
   * @return name
  **/
  @ApiModelProperty(value = "name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingAccountStatus billingAccountStatus = (BillingAccountStatus) o;
    return Objects.equals(this.code, billingAccountStatus.code) &&
        Objects.equals(this.accountStatusDescription, billingAccountStatus.accountStatusDescription) &&
        Objects.equals(this.name, billingAccountStatus.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, accountStatusDescription, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingAccountStatus {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    accountStatusDescription: ").append(toIndentedString(accountStatusDescription)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

