/*
 * BillingAccountsSearch
 * This service returns an account used for billing purposes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: shay.soifer@amdocs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.subscriber;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BillInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-08T11:56:47.701-05:00")
public class BillInfo {
  @SerializedName("billCycleStartDate")
  private String billCycleStartDate = null;

  @SerializedName("billCycleEndDate")
  private String billCycleEndDate = null;

  @SerializedName("autoPay")
  private String autoPay = null;

  public BillInfo billCycleStartDate(String billCycleStartDate) {
    this.billCycleStartDate = billCycleStartDate;
    return this;
  }

   /**
   * The cycle start date of the last confirmd bill
   * @return billCycleStartDate
  **/
  @ApiModelProperty(value = "The cycle start date of the last confirmd bill")
  public String getBillCycleStartDate() {
    return billCycleStartDate;
  }

  public void setBillCycleStartDate(String billCycleStartDate) {
    this.billCycleStartDate = billCycleStartDate;
  }

  public BillInfo billCycleEndDate(String billCycleEndDate) {
    this.billCycleEndDate = billCycleEndDate;
    return this;
  }

   /**
   * The cycle end date of the last confirmd bill
   * @return billCycleEndDate
  **/
  @ApiModelProperty(value = "The cycle end date of the last confirmd bill")
  public String getBillCycleEndDate() {
    return billCycleEndDate;
  }

  public void setBillCycleEndDate(String billCycleEndDate) {
    this.billCycleEndDate = billCycleEndDate;
  }

  public BillInfo autoPay(String autoPay) {
    this.autoPay = autoPay;
    return this;
  }

   /**
   * An indicator to state if the financial account is registered to autopay. in case the indicator is &#39;R&#39; the value set to &#39;opt-out&#39;, otherwise &#39;opt-in&#39;
   * @return autoPay
  **/
  @ApiModelProperty(value = "An indicator to state if the financial account is registered to autopay. in case the indicator is 'R' the value set to 'opt-out', otherwise 'opt-in'")
  public String getAutoPay() {
    return autoPay;
  }

  public void setAutoPay(String autoPay) {
    this.autoPay = autoPay;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillInfo billInfo = (BillInfo) o;
    return Objects.equals(this.billCycleStartDate, billInfo.billCycleStartDate) &&
        Objects.equals(this.billCycleEndDate, billInfo.billCycleEndDate) &&
        Objects.equals(this.autoPay, billInfo.autoPay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billCycleStartDate, billCycleEndDate, autoPay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillInfo {\n");
    
    sb.append("    billCycleStartDate: ").append(toIndentedString(billCycleStartDate)).append("\n");
    sb.append("    billCycleEndDate: ").append(toIndentedString(billCycleEndDate)).append("\n");
    sb.append("    autoPay: ").append(toIndentedString(autoPay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

