/*
 * BillingAccountsSearch
 * This service returns an account used for billing purposes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: shay.soifer@amdocs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.subscriber;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Error object.
 */
@ApiModel(description = "Error object.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-08T11:56:47.701-05:00")
public class Error {
  @SerializedName("code")
  private String code = null;

  @SerializedName("userMessage")
  private String userMessage = null;

  @SerializedName("systemMessage")
  private String systemMessage = null;

  public Error code(String code) {
    this.code = code;
    return this;
  }

   /**
   * A specific T-Mobile error code.
   * @return code
  **/
  @ApiModelProperty(value = "A specific T-Mobile error code.")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Error userMessage(String userMessage) {
    this.userMessage = userMessage;
    return this;
  }

   /**
   * A human-readable message describing the error.
   * @return userMessage
  **/
  @ApiModelProperty(value = "A human-readable message describing the error.")
  public String getUserMessage() {
    return userMessage;
  }

  public void setUserMessage(String userMessage) {
    this.userMessage = userMessage;
  }

  public Error systemMessage(String systemMessage) {
    this.systemMessage = systemMessage;
    return this;
  }

   /**
   * Backend system error message.
   * @return systemMessage
  **/
  @ApiModelProperty(value = "Backend system error message.")
  public String getSystemMessage() {
    return systemMessage;
  }

  public void setSystemMessage(String systemMessage) {
    this.systemMessage = systemMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Error error = (Error) o;
    return Objects.equals(this.code, error.code) &&
        Objects.equals(this.userMessage, error.userMessage) &&
        Objects.equals(this.systemMessage, error.systemMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, userMessage, systemMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Error {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    userMessage: ").append(toIndentedString(userMessage)).append("\n");
    sb.append("    systemMessage: ").append(toIndentedString(systemMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

