/*
 * Promotions - Ban and Subscriber Level Attributes
 * This document describes Promotion APIs that retrieve information about a subscriber and its ban (services - SOCs/Rate Plans, activation date etc)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.subscriber;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.subscriber.AccountTypeRef;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FinancialAccountProfile
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-08T15:53:35.582-05:00")
public class FinancialAccountProfile {
  @SerializedName("status")
  private String status = null;

  @SerializedName("account")
  private AccountTypeRef account = null;

  @SerializedName("notificationMsisdn")
  private String notificationMsisdn = null;

  @SerializedName("totalActiveSuspendedLines")
  private Integer totalActiveSuspendedLines = null;

  public FinancialAccountProfile status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public FinancialAccountProfile account(AccountTypeRef account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @ApiModelProperty(value = "")
  public AccountTypeRef getAccount() {
    return account;
  }

  public void setAccount(AccountTypeRef account) {
    this.account = account;
  }

  public FinancialAccountProfile notificationMsisdn(String notificationMsisdn) {
    this.notificationMsisdn = notificationMsisdn;
    return this;
  }

   /**
   * Get notificationMsisdn
   * @return notificationMsisdn
  **/
  @ApiModelProperty(value = "")
  public String getNotificationMsisdn() {
    return notificationMsisdn;
  }

  public void setNotificationMsisdn(String notificationMsisdn) {
    this.notificationMsisdn = notificationMsisdn;
  }

  public FinancialAccountProfile totalActiveSuspendedLines(Integer totalActiveSuspendedLines) {
    this.totalActiveSuspendedLines = totalActiveSuspendedLines;
    return this;
  }

   /**
   * Get totalActiveSuspendedLines
   * @return totalActiveSuspendedLines
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalActiveSuspendedLines() {
    return totalActiveSuspendedLines;
  }

  public void setTotalActiveSuspendedLines(Integer totalActiveSuspendedLines) {
    this.totalActiveSuspendedLines = totalActiveSuspendedLines;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinancialAccountProfile financialAccountProfile = (FinancialAccountProfile) o;
    return Objects.equals(this.status, financialAccountProfile.status) &&
        Objects.equals(this.account, financialAccountProfile.account) &&
        Objects.equals(this.notificationMsisdn, financialAccountProfile.notificationMsisdn) &&
        Objects.equals(this.totalActiveSuspendedLines, financialAccountProfile.totalActiveSuspendedLines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, account, notificationMsisdn, totalActiveSuspendedLines);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FinancialAccountProfile {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    notificationMsisdn: ").append(toIndentedString(notificationMsisdn)).append("\n");
    sb.append("    totalActiveSuspendedLines: ").append(toIndentedString(totalActiveSuspendedLines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

