/*
 * BillingAccountsSearch
 * This service returns an account used for billing purposes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: shay.soifer@amdocs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.subscriber;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-08T11:56:47.701-05:00")
public class Phone {
  @SerializedName("contactExtention")
  private String contactExtention = null;

  @SerializedName("contactFax")
  private String contactFax = null;

  @SerializedName("contactPhone")
  private String contactPhone = null;

  @SerializedName("home")
  private String home = null;

  @SerializedName("other")
  private String other = null;

  @SerializedName("workExtension")
  private String workExtension = null;

  @SerializedName("workPhone")
  private String workPhone = null;

  public Phone contactExtention(String contactExtention) {
    this.contactExtention = contactExtention;
    return this;
  }

   /**
   * contactExtention
   * @return contactExtention
  **/
  @ApiModelProperty(value = "contactExtention")
  public String getContactExtention() {
    return contactExtention;
  }

  public void setContactExtention(String contactExtention) {
    this.contactExtention = contactExtention;
  }

  public Phone contactFax(String contactFax) {
    this.contactFax = contactFax;
    return this;
  }

   /**
   * contactFax
   * @return contactFax
  **/
  @ApiModelProperty(value = "contactFax")
  public String getContactFax() {
    return contactFax;
  }

  public void setContactFax(String contactFax) {
    this.contactFax = contactFax;
  }

  public Phone contactPhone(String contactPhone) {
    this.contactPhone = contactPhone;
    return this;
  }

   /**
   * contactPhone
   * @return contactPhone
  **/
  @ApiModelProperty(value = "contactPhone")
  public String getContactPhone() {
    return contactPhone;
  }

  public void setContactPhone(String contactPhone) {
    this.contactPhone = contactPhone;
  }

  public Phone home(String home) {
    this.home = home;
    return this;
  }

   /**
   * home
   * @return home
  **/
  @ApiModelProperty(value = "home")
  public String getHome() {
    return home;
  }

  public void setHome(String home) {
    this.home = home;
  }

  public Phone other(String other) {
    this.other = other;
    return this;
  }

   /**
   * other
   * @return other
  **/
  @ApiModelProperty(value = "other")
  public String getOther() {
    return other;
  }

  public void setOther(String other) {
    this.other = other;
  }

  public Phone workExtension(String workExtension) {
    this.workExtension = workExtension;
    return this;
  }

   /**
   * workExtension
   * @return workExtension
  **/
  @ApiModelProperty(value = "workExtension")
  public String getWorkExtension() {
    return workExtension;
  }

  public void setWorkExtension(String workExtension) {
    this.workExtension = workExtension;
  }

  public Phone workPhone(String workPhone) {
    this.workPhone = workPhone;
    return this;
  }

   /**
   * workPhone
   * @return workPhone
  **/
  @ApiModelProperty(value = "workPhone")
  public String getWorkPhone() {
    return workPhone;
  }

  public void setWorkPhone(String workPhone) {
    this.workPhone = workPhone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Phone phone = (Phone) o;
    return Objects.equals(this.contactExtention, phone.contactExtention) &&
        Objects.equals(this.contactFax, phone.contactFax) &&
        Objects.equals(this.contactPhone, phone.contactPhone) &&
        Objects.equals(this.home, phone.home) &&
        Objects.equals(this.other, phone.other) &&
        Objects.equals(this.workExtension, phone.workExtension) &&
        Objects.equals(this.workPhone, phone.workPhone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contactExtention, contactFax, contactPhone, home, other, workExtension, workPhone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Phone {\n");
    
    sb.append("    contactExtention: ").append(toIndentedString(contactExtention)).append("\n");
    sb.append("    contactFax: ").append(toIndentedString(contactFax)).append("\n");
    sb.append("    contactPhone: ").append(toIndentedString(contactPhone)).append("\n");
    sb.append("    home: ").append(toIndentedString(home)).append("\n");
    sb.append("    other: ").append(toIndentedString(other)).append("\n");
    sb.append("    workExtension: ").append(toIndentedString(workExtension)).append("\n");
    sb.append("    workPhone: ").append(toIndentedString(workPhone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

