/*
 * Promotions - Ban and Subscriber Level Attributes
 * This document describes Promotion APIs that retrieve information about a subscriber and its ban (services - SOCs/Rate Plans, activation date etc)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.subscriber;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ServicesRef
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-08T15:53:35.582-05:00")
public class ServicesRef {
  @SerializedName("code")
  private String code = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("socDescription")
  private String socDescription = null;

  @SerializedName("socEffectiveDate")
  private String socEffectiveDate = null;

  @SerializedName("socExpirationDate")
  private String socExpirationDate = null;

  public ServicesRef code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ServicesRef type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ServicesRef socDescription(String socDescription) {
    this.socDescription = socDescription;
    return this;
  }

   /**
   * Get socDescription
   * @return socDescription
  **/
  @ApiModelProperty(value = "")
  public String getSocDescription() {
    return socDescription;
  }

  public void setSocDescription(String socDescription) {
    this.socDescription = socDescription;
  }

  public ServicesRef socEffectiveDate(String socEffectiveDate) {
    this.socEffectiveDate = socEffectiveDate;
    return this;
  }

   /**
   * Get socEffectiveDate
   * @return socEffectiveDate
  **/
  @ApiModelProperty(value = "")
  public String getSocEffectiveDate() {
    return socEffectiveDate;
  }

  public void setSocEffectiveDate(String socEffectiveDate) {
    this.socEffectiveDate = socEffectiveDate;
  }

  public ServicesRef socExpirationDate(String socExpirationDate) {
    this.socExpirationDate = socExpirationDate;
    return this;
  }

   /**
   * Get socExpirationDate
   * @return socExpirationDate
  **/
  @ApiModelProperty(value = "")
  public String getSocExpirationDate() {
    return socExpirationDate;
  }

  public void setSocExpirationDate(String socExpirationDate) {
    this.socExpirationDate = socExpirationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServicesRef servicesRef = (ServicesRef) o;
    return Objects.equals(this.code, servicesRef.code) &&
        Objects.equals(this.type, servicesRef.type) &&
        Objects.equals(this.socDescription, servicesRef.socDescription) &&
        Objects.equals(this.socEffectiveDate, servicesRef.socEffectiveDate) &&
        Objects.equals(this.socExpirationDate, servicesRef.socExpirationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, type, socDescription, socEffectiveDate, socExpirationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServicesRef {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    socDescription: ").append(toIndentedString(socDescription)).append("\n");
    sb.append("    socEffectiveDate: ").append(toIndentedString(socEffectiveDate)).append("\n");
    sb.append("    socExpirationDate: ").append(toIndentedString(socExpirationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

