/*
 * Promotions - Ban and Subscriber Level Attributes
 * This document describes Promotion APIs that retrieve information about a subscriber and its ban (services - SOCs/Rate Plans, activation date etc)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.tmobile.finance.subscriber;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tmobile.finance.subscriber.FinancialAccountProfile;
import com.tmobile.finance.subscriber.SubscriberProfile;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SubscriberProfileResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-08T15:53:35.582-05:00")
public class SubscriberProfileResponse {
  @SerializedName("financialAccount")
  private FinancialAccountProfile financialAccount = null;

  @SerializedName("subscriber")
  private SubscriberProfile subscriber = null;

  public SubscriberProfileResponse financialAccount(FinancialAccountProfile financialAccount) {
    this.financialAccount = financialAccount;
    return this;
  }

   /**
   * Get financialAccount
   * @return financialAccount
  **/
  @ApiModelProperty(value = "")
  public FinancialAccountProfile getFinancialAccount() {
    return financialAccount;
  }

  public void setFinancialAccount(FinancialAccountProfile financialAccount) {
    this.financialAccount = financialAccount;
  }

  public SubscriberProfileResponse subscriber(SubscriberProfile subscriber) {
    this.subscriber = subscriber;
    return this;
  }

   /**
   * Get subscriber
   * @return subscriber
  **/
  @ApiModelProperty(value = "")
  public SubscriberProfile getSubscriber() {
    return subscriber;
  }

  public void setSubscriber(SubscriberProfile subscriber) {
    this.subscriber = subscriber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriberProfileResponse subscriberProfileResponse = (SubscriberProfileResponse) o;
    return Objects.equals(this.financialAccount, subscriberProfileResponse.financialAccount) &&
        Objects.equals(this.subscriber, subscriberProfileResponse.subscriber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(financialAccount, subscriber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriberProfileResponse {\n");
    
    sb.append("    financialAccount: ").append(toIndentedString(financialAccount)).append("\n");
    sb.append("    subscriber: ").append(toIndentedString(subscriber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

